import { SXBilibili } from "./custom/bilibili"
import { SXNeteaseCloudMusic } from "./custom/neteasecloudmusic"

import type { BrandIconSpec } from "./types"

export const brandSpecs: BrandIconSpec[] = [
  {
    prefix: "lg",
    slug: "paypal",
    title: "PayPal",
    hex: "#003087",
    keywords: ["payment"],
    loadIcon: () => import("@icongo/lg/esm/LGPaypal").then((module) => module.LGPaypal),
  },
  {
    prefix: "lg",
    slug: "stripe",
    title: "Stripe",
    hex: "#635BFF",
    keywords: ["payment"],
    loadIcon: () => import("@icongo/lg/esm/LGStripe").then((module) => module.LGStripe),
  },
  {
    prefix: "lg",
    slug: "visa",
    title: "Visa",
    hex: "#1434CB",
    keywords: ["payment", "card"],
    loadIcon: () => import("@icongo/lg/esm/LGVisa").then((module) => module.LGVisa),
  },
  {
    prefix: "lg",
    slug: "mastercard",
    title: "Mastercard",
    hex: "#EB001B",
    keywords: ["payment", "card"],
    loadIcon: () => import("@icongo/lg/esm/LGMastercard").then((module) => module.LGMastercard),
  },
  {
    prefix: "lg",
    slug: "amex",
    title: "American Express",
    hex: "#2E77BC",
    keywords: ["payment", "card", "american express"],
    loadIcon: () => import("@icongo/lg/esm/LGAmex").then((module) => module.LGAmex),
  },
  {
    prefix: "lg",
    slug: "jcb",
    title: "JCB",
    hex: "#0B4EA2",
    keywords: ["payment", "card"],
    loadIcon: () => import("@icongo/lg/esm/LGJcb").then((module) => module.LGJcb),
  },
  {
    prefix: "lg",
    slug: "unionpay",
    title: "UnionPay",
    hex: "#00447C",
    keywords: ["payment", "card", "银联"],
    loadIcon: () => import("@icongo/lg/esm/LGUnionpay").then((module) => module.LGUnionpay),
  },
  {
    prefix: "lg",
    slug: "applepay",
    title: "Apple Pay",
    hex: "#000000",
    keywords: ["payment", "wallet"],
    loadIcon: () => import("@icongo/lg/esm/LGApplePay").then((module) => module.LGApplePay),
  },
  {
    prefix: "lg",
    slug: "googlepay",
    title: "Google Pay",
    hex: "#4285F4",
    keywords: ["payment", "wallet"],
    loadIcon: () => import("@icongo/lg/esm/LGGooglePayIcon").then((module) => module.LGGooglePayIcon),
  },
  {
    prefix: "lg",
    slug: "openai",
    title: "OpenAI",
    hex: "#412991",
    keywords: ["chatgpt", "gpt", "ai"],
    loadIcon: () => import("@icongo/lg/esm/LGOpenaiIcon").then((module) => module.LGOpenaiIcon),
  },
  {
    prefix: "lg",
    slug: "google",
    title: "Google",
    hex: "#4285F4",
    keywords: ["search", "workspace"],
    loadIcon: () => import("@icongo/lg/esm/LGGoogleIcon").then((module) => module.LGGoogleIcon),
  },
  {
    prefix: "lg",
    slug: "googlecloud",
    title: "Google Cloud",
    hex: "#4285F4",
    keywords: ["gcp", "cloud"],
    loadIcon: () => import("@icongo/lg/esm/LGGoogleCloud").then((module) => module.LGGoogleCloud),
  },
  {
    prefix: "lg",
    slug: "cloudflare",
    title: "Cloudflare",
    hex: "#F38020",
    keywords: ["cloud", "cdn"],
    loadIcon: () => import("@icongo/lg/esm/LGCloudflare").then((module) => module.LGCloudflare),
  },
  {
    prefix: "lg",
    slug: "digitalocean",
    title: "DigitalOcean",
    hex: "#0080FF",
    keywords: ["cloud"],
    loadIcon: () => import("@icongo/vl/esm/VLDigitalocean").then((module) => module.VLDigitalocean),
  },
  {
    prefix: "lg",
    slug: "vercel",
    title: "Vercel",
    hex: "#000000",
    keywords: ["hosting"],
    loadIcon: () => import("@icongo/lg/esm/LGVercelIcon").then((module) => module.LGVercelIcon),
  },
  {
    prefix: "lg",
    slug: "netlify",
    title: "Netlify",
    hex: "#00C7B7",
    keywords: ["hosting"],
    loadIcon: () => import("@icongo/lg/esm/LGNetlify").then((module) => module.LGNetlify),
  },
  {
    prefix: "lg",
    slug: "aws",
    title: "AWS",
    hex: "#FF9900",
    keywords: ["amazon cloud", "cloud"],
    loadIcon: () => import("@icongo/lg/esm/LGAws").then((module) => module.LGAws),
  },
  {
    prefix: "lg",
    slug: "oracle",
    title: "Oracle",
    hex: "#F80000",
    keywords: ["cloud"],
    loadIcon: () => import("@icongo/vl/esm/VLOracle").then((module) => module.VLOracle),
  },
  {
    prefix: "lg",
    slug: "ibm",
    title: "IBM",
    hex: "#1261FE",
    keywords: ["cloud"],
    loadIcon: () => import("@icongo/lg/esm/LGIbm").then((module) => module.LGIbm),
  },
  {
    prefix: "lg",
    slug: "namecheap",
    title: "Namecheap",
    hex: "#FF6A00",
    keywords: ["domain"],
    loadIcon: () => import("@icongo/lg/esm/LGNamecheap").then((module) => module.LGNamecheap),
  },
  {
    prefix: "lg",
    slug: "github",
    title: "GitHub",
    hex: "#181717",
    keywords: ["code", "git"],
    loadIcon: () => import("@icongo/lg/esm/LGGithubIcon").then((module) => module.LGGithubIcon),
  },
  {
    prefix: "lg",
    slug: "gitlab",
    title: "GitLab",
    hex: "#FC6D26",
    keywords: ["code", "git"],
    loadIcon: () => import("@icongo/lg/esm/LGGitlab").then((module) => module.LGGitlab),
  },
  {
    prefix: "lg",
    slug: "docker",
    title: "Docker",
    hex: "#2496ED",
    keywords: ["container"],
    loadIcon: () => import("@icongo/lg/esm/LGDockerIcon").then((module) => module.LGDockerIcon),
  },
  {
    prefix: "lg",
    slug: "figma",
    title: "Figma",
    hex: "#A259FF",
    keywords: ["design"],
    loadIcon: () => import("@icongo/lg/esm/LGFigma").then((module) => module.LGFigma),
  },
  {
    prefix: "lg",
    slug: "postman",
    title: "Postman",
    hex: "#FF6C37",
    keywords: ["api"],
    loadIcon: () => import("@icongo/lg/esm/LGPostmanIcon").then((module) => module.LGPostmanIcon),
  },
  {
    prefix: "lg",
    slug: "insomnia",
    title: "Insomnia",
    hex: "#4000BF",
    keywords: ["api"],
    loadIcon: () => import("@icongo/lg/esm/LGInsomnia").then((module) => module.LGInsomnia),
  },
  {
    prefix: "lg",
    slug: "jira",
    title: "Jira",
    hex: "#0052CC",
    keywords: ["project"],
    loadIcon: () => import("@icongo/lg/esm/LGJira").then((module) => module.LGJira),
  },
  {
    prefix: "lg",
    slug: "trello",
    title: "Trello",
    hex: "#0052CC",
    keywords: ["project"],
    loadIcon: () => import("@icongo/lg/esm/LGTrello").then((module) => module.LGTrello),
  },
  {
    prefix: "lg",
    slug: "asana",
    title: "Asana",
    hex: "#F06A6A",
    keywords: ["project"],
    loadIcon: () => import("@icongo/lg/esm/LGAsanaIcon").then((module) => module.LGAsanaIcon),
  },
  {
    prefix: "lg",
    slug: "onepassword",
    title: "1Password",
    hex: "#0094F5",
    keywords: ["password manager", "security", "密码管理"],
    loadIcon: () => import("@icongo/vl/esm/VL1Password").then((module) => module.VL1Password),
  },
  {
    prefix: "lg",
    slug: "adidas",
    title: "Adidas",
    hex: "#000000",
    keywords: ["sportswear", "brand"],
    loadIcon: () => import("@icongo/vl/esm/VLAdidas").then((module) => module.VLAdidas),
  },
  {
    prefix: "lg",
    slug: "adobecreativecloud",
    title: "Adobe Creative Cloud",
    hex: "#DA1F26",
    keywords: ["adobe", "creative", "design", "创意云"],
    loadIcon: () => import("@icongo/vl/esm/VLAdobe").then((module) => module.VLAdobe),
  },
  {
    prefix: "lg",
    slug: "adobeaftereffects",
    title: "Adobe After Effects",
    hex: "#9999FF",
    keywords: ["adobe", "video", "motion", "ae"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeAfterEffects").then((module) => module.LGAdobeAfterEffects),
  },
  {
    prefix: "lg",
    slug: "adobeanimate",
    title: "Adobe Animate",
    hex: "#FF8B00",
    keywords: ["adobe", "animation"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeAnimate").then((module) => module.LGAdobeAnimate),
  },
  {
    prefix: "lg",
    slug: "adobedreamweaver",
    title: "Adobe Dreamweaver",
    hex: "#35FA00",
    keywords: ["adobe", "web", "development"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeDreamweaver").then((module) => module.LGAdobeDreamweaver),
  },
  {
    prefix: "lg",
    slug: "adobeillustrator",
    title: "Adobe Illustrator",
    hex: "#FF9A00",
    keywords: ["adobe", "vector", "design", "ai"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeIllustrator").then((module) => module.LGAdobeIllustrator),
  },
  {
    prefix: "lg",
    slug: "adobeincopy",
    title: "Adobe InCopy",
    hex: "#FF3366",
    keywords: ["adobe", "writing", "editorial"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeIncopy").then((module) => module.LGAdobeIncopy),
  },
  {
    prefix: "lg",
    slug: "adobeindesign",
    title: "Adobe InDesign",
    hex: "#FF3366",
    keywords: ["adobe", "layout", "publishing", "id"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeIndesign").then((module) => module.LGAdobeIndesign),
  },
  {
    prefix: "lg",
    slug: "adobelightroom",
    title: "Adobe Lightroom",
    hex: "#31A8FF",
    keywords: ["adobe", "photo", "editing", "lr"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeLightroom").then((module) => module.LGAdobeLightroom),
  },
  {
    prefix: "lg",
    slug: "adobephotoshop",
    title: "Adobe Photoshop",
    hex: "#31A8FF",
    keywords: ["adobe", "photo", "design", "ps"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobePhotoshop").then((module) => module.LGAdobePhotoshop),
  },
  {
    prefix: "lg",
    slug: "adobepremiere",
    title: "Adobe Premiere Pro",
    hex: "#9999FF",
    keywords: ["adobe", "video", "editing", "pr"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobePremiere").then((module) => module.LGAdobePremiere),
  },
  {
    prefix: "lg",
    slug: "adobexd",
    title: "Adobe XD",
    hex: "#FF61F6",
    keywords: ["adobe", "ux", "ui", "design"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeXd").then((module) => module.LGAdobeXd),
  },
  {
    prefix: "lg",
    slug: "airbnb",
    title: "Airbnb",
    hex: "#FF5A5F",
    keywords: ["travel", "booking", "住宿"],
    loadIcon: () => import("@icongo/lg/esm/LGAirbnbIcon").then((module) => module.LGAirbnbIcon),
  },
  {
    prefix: "lg",
    slug: "behance",
    title: "Behance",
    hex: "#1769FF",
    keywords: ["design", "portfolio"],
    loadIcon: () => import("@icongo/lg/esm/LGBehance").then((module) => module.LGBehance),
  },
  {
    prefix: "lg",
    slug: "bitwarden",
    title: "Bitwarden",
    hex: "#175DDC",
    keywords: ["password manager", "security", "密码管理"],
    loadIcon: () => import("@icongo/vl/esm/VLBitwarden").then((module) => module.VLBitwarden),
  },
  {
    prefix: "lg",
    slug: "box",
    title: "Box",
    hex: "#0061D5",
    keywords: ["cloud storage", "files"],
    loadIcon: () => import("@icongo/lg/esm/LGBox").then((module) => module.LGBox),
  },
  {
    prefix: "lg",
    slug: "canva",
    title: "Canva",
    hex: "#00C4CC",
    keywords: ["design", "graphics"],
    loadIcon: () => import("@icongo/vl/esm/VLCanva").then((module) => module.VLCanva),
  },
  {
    prefix: "lg",
    slug: "chatgpt",
    title: "ChatGPT",
    hex: "#10A37F",
    keywords: ["openai", "gpt", "ai", "chatbot"],
    loadIcon: () => import("@icongo/lg/esm/LGOpenaiIcon").then((module) => module.LGOpenaiIcon),
  },
  {
    prefix: "lg",
    slug: "coinbase",
    title: "Coinbase",
    hex: "#0052FF",
    keywords: ["crypto", "exchange", "coin"],
    loadIcon: () => import("@icongo/vl/esm/VLCoinbase").then((module) => module.VLCoinbase),
  },
  {
    prefix: "lg",
    slug: "dropbox",
    title: "Dropbox",
    hex: "#0061FF",
    keywords: ["cloud storage", "files"],
    loadIcon: () => import("@icongo/lg/esm/LGDropbox").then((module) => module.LGDropbox),
  },
  {
    prefix: "lg",
    slug: "evernote",
    title: "Evernote",
    hex: "#00A82D",
    keywords: ["notes", "productivity"],
    loadIcon: () => import("@icongo/vl/esm/VLEvernote").then((module) => module.VLEvernote),
  },
  {
    prefix: "lg",
    slug: "expressvpn",
    title: "ExpressVPN",
    hex: "#DA3940",
    keywords: ["vpn", "privacy", "security"],
    loadIcon: () => import("@icongo/lg/esm/LGExpress").then((module) => module.LGExpress),
  },
  {
    prefix: "lg",
    slug: "feedly",
    title: "Feedly",
    hex: "#2BB24C",
    keywords: ["rss", "reader", "news"],
    loadIcon: () => import("@icongo/vl/esm/VLFeedly").then((module) => module.VLFeedly),
  },
  {
    prefix: "lg",
    slug: "fontawesome",
    title: "Font Awesome",
    hex: "#528DD7",
    keywords: ["icons", "font", "ui"],
    loadIcon: () => import("@icongo/lg/esm/LGFontAwesome").then((module) => module.LGFontAwesome),
  },
  {
    prefix: "lg",
    slug: "godaddy",
    title: "GoDaddy",
    hex: "#1BDBDB",
    keywords: ["domain", "hosting"],
    loadIcon: () => import("@icongo/vl/esm/VLGodaddy").then((module) => module.VLGodaddy),
  },
  {
    prefix: "lg",
    slug: "googleone",
    title: "Google One",
    hex: "#4285F4",
    keywords: ["google", "cloud storage", "drive"],
    loadIcon: () => import("@icongo/lg/esm/LGGoogleOne").then((module) => module.LGGoogleOne),
  },
  {
    prefix: "lg",
    slug: "grammarly",
    title: "Grammarly",
    hex: "#15C39A",
    keywords: ["writing", "assistant", "grammar"],
    loadIcon: () => import("@icongo/lg/esm/LGGrammarlyIcon").then((module) => module.LGGrammarlyIcon),
  },
  {
    prefix: "lg",
    slug: "udemy",
    title: "Udemy",
    hex: "#A435F0",
    keywords: ["learning", "courses", "education"],
    loadIcon: () => import("@icongo/lg/esm/LGUdemyIcon").then((module) => module.LGUdemyIcon),
  },
  {
    prefix: "lg",
    slug: "jetbrains",
    title: "JetBrains",
    hex: "#000000",
    keywords: ["ide", "developer tools", "jetbrains"],
    loadIcon: () => import("@icongo/lg/esm/LGJetbrainsIcon").then((module) => module.LGJetbrainsIcon),
  },
  {
    prefix: "lg",
    slug: "intellijidea",
    title: "IntelliJ IDEA",
    hex: "#000000",
    keywords: ["jetbrains", "ide", "java", "intellij"],
    loadIcon: () => import("@icongo/lg/esm/LGIntellijIdea").then((module) => module.LGIntellijIdea),
  },
  {
    prefix: "lg",
    slug: "lastpass",
    title: "LastPass",
    hex: "#D32D27",
    keywords: ["password manager", "security", "密码管理"],
    loadIcon: () => import("@icongo/vl/esm/VLLastpass").then((module) => module.VLLastpass),
  },
  {
    prefix: "lg",
    slug: "linkedin",
    title: "LinkedIn",
    hex: "#0A66C2",
    keywords: ["social", "network", "career"],
    loadIcon: () => import("@icongo/lg/esm/LGLinkedinIcon").then((module) => module.LGLinkedinIcon),
  },
  {
    prefix: "lg",
    slug: "medium",
    title: "Medium",
    hex: "#12100E",
    keywords: ["blog", "writing", "articles"],
    loadIcon: () => import("@icongo/lg/esm/LGMediumIcon").then((module) => module.LGMediumIcon),
  },
  {
    prefix: "lg",
    slug: "meta",
    title: "Meta",
    hex: "#0866FF",
    keywords: ["facebook", "social", "meta"],
    loadIcon: () => import("@icongo/lg/esm/LGFacebook").then((module) => module.LGFacebook),
  },
  {
    prefix: "lg",
    slug: "nytimes",
    title: "New York Times",
    hex: "#000000",
    keywords: ["news", "times", "newspaper"],
    loadIcon: () => import("@icongo/vl/esm/VLNytimes").then((module) => module.VLNytimes),
  },
  {
    prefix: "lg",
    slug: "times",
    title: "Times",
    hex: "#000000",
    keywords: ["nytimes", "times", "news", "newspaper"],
    loadIcon: () => import("@icongo/vl/esm/VLNytimes").then((module) => module.VLNytimes),
  },
  {
    prefix: "lg",
    slug: "patreon",
    title: "Patreon",
    hex: "#FF424D",
    keywords: ["creator", "membership", "subscription"],
    loadIcon: () => import("@icongo/lg/esm/LGPatreon").then((module) => module.LGPatreon),
  },
  {
    prefix: "lg",
    slug: "pinterest",
    title: "Pinterest",
    hex: "#E60023",
    keywords: ["social", "inspiration", "images"],
    loadIcon: () => import("@icongo/lg/esm/LGPinterest").then((module) => module.LGPinterest),
  },
  {
    prefix: "lg",
    slug: "proton",
    title: "Proton",
    hex: "#6D4AFF",
    keywords: ["protonmail", "privacy", "email"],
    loadIcon: () => import("@icongo/vl/esm/VLProtonmail").then((module) => module.VLProtonmail),
  },
  {
    prefix: "lg",
    slug: "revolut",
    title: "Revolut",
    hex: "#191C1F",
    keywords: ["banking", "finance", "payment"],
    loadIcon: () => import("@icongo/vl/esm/VLRevolut").then((module) => module.VLRevolut),
  },
  {
    prefix: "lg",
    slug: "twitter",
    title: "Twitter / X",
    hex: "#000000",
    keywords: ["twitter", "x", "social", "x premium"],
    loadIcon: () => import("@icongo/lg/esm/LGTwitter").then((module) => module.LGTwitter),
  },
  {
    prefix: "lg",
    slug: "x",
    title: "X",
    hex: "#000000",
    keywords: ["twitter", "x", "social"],
    loadIcon: () => import("@icongo/lg/esm/LGTwitter").then((module) => module.LGTwitter),
  },
  {
    prefix: "lg",
    slug: "xpremium",
    title: "X Premium",
    hex: "#000000",
    keywords: ["x", "twitter", "subscription", "premium"],
    loadIcon: () => import("@icongo/lg/esm/LGTwitter").then((module) => module.LGTwitter),
  },
  {
    prefix: "lg",
    slug: "uber",
    title: "Uber",
    hex: "#000000",
    keywords: ["ride", "transport", "travel"],
    loadIcon: () => import("@icongo/vl/esm/VLUberLudwig").then((module) => module.VLUberLudwig),
  },
  {
    prefix: "lg",
    slug: "walmart",
    title: "Walmart",
    hex: "#0071CE",
    keywords: ["shopping", "retail", "groceries"],
    loadIcon: () => import("@icongo/vl/esm/VLWalmart").then((module) => module.VLWalmart),
  },
  {
    prefix: "lg",
    slug: "wise",
    title: "Wise",
    hex: "#00B9FF",
    keywords: ["transferwise", "payment", "money transfer"],
    loadIcon: () => import("@icongo/vl/esm/VLTransferwise").then((module) => module.VLTransferwise),
  },
  {
    prefix: "lg",
    slug: "xbox",
    title: "Xbox",
    hex: "#107C10",
    keywords: ["gaming", "microsoft", "console"],
    loadIcon: () => import("@icongo/vl/esm/VLXbox").then((module) => module.VLXbox),
  },
  {
    prefix: "lg",
    slug: "zoom",
    title: "Zoom",
    hex: "#2D8CFF",
    keywords: ["meeting", "video call", "conference"],
    loadIcon: () => import("@icongo/vl/esm/VLZoomus").then((module) => module.VLZoomus),
  },
  {
    prefix: "lg",
    slug: "icloud",
    title: "iCloud",
    hex: "#0A84FF",
    keywords: ["apple", "cloud storage", "icloud"],
    loadIcon: () => import("@icongo/vl/esm/VLApple").then((module) => module.VLApple),
  },
  {
    prefix: "lg",
    slug: "audible",
    title: "Audible",
    hex: "#F7991C",
    keywords: ["audiobook", "audio", "amazon"],
    loadIcon: () => import("@icongo/si/esm/SIAudible").then((module) => module.SIAudible),
  },
  {
    prefix: "lg",
    slug: "bitly",
    title: "Bitly",
    hex: "#EE6123",
    keywords: ["link shortener", "url", "marketing"],
    loadIcon: () => import("@icongo/si/esm/SIBitly").then((module) => module.SIBitly),
  },
  {
    prefix: "lg",
    slug: "cashapp",
    title: "Cash App",
    hex: "#00D632",
    keywords: ["payment", "wallet", "finance"],
    loadIcon: () => import("@icongo/si/esm/SICashapp").then((module) => module.SICashapp),
  },
  {
    prefix: "lg",
    slug: "chase",
    title: "Chase",
    hex: "#117ACA",
    keywords: ["bank", "payment", "finance"],
    loadIcon: () => import("@icongo/si/esm/SIChase").then((module) => module.SIChase),
  },
  {
    prefix: "lg",
    slug: "dhl",
    title: "DHL",
    hex: "#D40511",
    keywords: ["shipping", "logistics", "delivery"],
    loadIcon: () => import("@icongo/si/esm/SIDhl").then((module) => module.SIDhl),
  },
  {
    prefix: "lg",
    slug: "duolingo",
    title: "Duolingo",
    hex: "#58CC02",
    keywords: ["language", "learning", "education"],
    loadIcon: () => import("@icongo/si/esm/SIDuolingo").then((module) => module.SIDuolingo),
  },
  {
    prefix: "lg",
    slug: "epicgames",
    title: "Epic Games",
    hex: "#313131",
    keywords: ["gaming", "games", "store"],
    loadIcon: () => import("@icongo/si/esm/SIEpicgames").then((module) => module.SIEpicgames),
  },
  {
    prefix: "lg",
    slug: "hbomax",
    title: "HBO Max",
    hex: "#5822B4",
    keywords: ["hbo", "max", "streaming", "video"],
    loadIcon: () => import("@icongo/si/esm/SIHbo").then((module) => module.SIHbo),
  },
  {
    prefix: "lg",
    slug: "max",
    title: "Max",
    hex: "#002BE7",
    keywords: ["hbo max", "streaming", "video"],
    loadIcon: () => import("@icongo/si/esm/SIMax").then((module) => module.SIMax),
  },
  {
    prefix: "lg",
    slug: "hulu",
    title: "Hulu",
    hex: "#1CE783",
    keywords: ["streaming", "video"],
    loadIcon: () => import("@icongo/si/esm/SIHulu").then((module) => module.SIHulu),
  },
  {
    prefix: "lg",
    slug: "instapaper",
    title: "Instapaper",
    hex: "#1F1F1F",
    keywords: ["read later", "articles", "news"],
    loadIcon: () => import("@icongo/si/esm/SIInstapaper").then((module) => module.SIInstapaper),
  },
  {
    prefix: "lg",
    slug: "mega",
    title: "Mega",
    hex: "#D9272E",
    keywords: ["cloud storage", "files"],
    loadIcon: () => import("@icongo/si/esm/SIMega").then((module) => module.SIMega),
  },
  {
    prefix: "lg",
    slug: "nintendo",
    title: "Nintendo",
    hex: "#E60012",
    keywords: ["gaming", "console", "switch"],
    loadIcon: () => import("@icongo/si/esm/SINintendo").then((module) => module.SINintendo),
  },
  {
    prefix: "lg",
    slug: "nordvpn",
    title: "NordVPN",
    hex: "#4687FF",
    keywords: ["vpn", "privacy", "security"],
    loadIcon: () => import("@icongo/si/esm/SINordvpn").then((module) => module.SINordvpn),
  },
  {
    prefix: "lg",
    slug: "notion",
    title: "Notion",
    hex: "#000000",
    keywords: ["notes", "workspace", "productivity"],
    loadIcon: () => import("@icongo/si/esm/SINotion").then((module) => module.SINotion),
  },
  {
    prefix: "lg",
    slug: "obsidian",
    title: "Obsidian",
    hex: "#7C3AED",
    keywords: ["notes", "markdown", "knowledge"],
    loadIcon: () => import("@icongo/si/esm/SIObsidian").then((module) => module.SIObsidian),
  },
  {
    prefix: "lg",
    slug: "openvpn",
    title: "OpenVPN",
    hex: "#EA7E20",
    keywords: ["vpn", "privacy", "security"],
    loadIcon: () => import("@icongo/si/esm/SIOpenvpn").then((module) => module.SIOpenvpn),
  },
  {
    prefix: "lg",
    slug: "playstation",
    title: "PlayStation",
    hex: "#003791",
    keywords: ["gaming", "console", "playstation"],
    loadIcon: () => import("@icongo/si/esm/SIPlaystation").then((module) => module.SIPlaystation),
  },
  {
    prefix: "lg",
    slug: "tmobile",
    title: "T-Mobile",
    hex: "#E20074",
    keywords: ["telecom", "mobile", "carrier"],
    loadIcon: () => import("@icongo/si/esm/SITmobile").then((module) => module.SITmobile),
  },
  {
    prefix: "lg",
    slug: "ubisoft",
    title: "Ubisoft",
    hex: "#000000",
    keywords: ["gaming", "games", "publisher"],
    loadIcon: () => import("@icongo/si/esm/SIUbisoft").then((module) => module.SIUbisoft),
  },
  {
    prefix: "lg",
    slug: "unsplash",
    title: "Unsplash",
    hex: "#000000",
    keywords: ["photos", "images", "stock"],
    loadIcon: () => import("@icongo/si/esm/SIUnsplash").then((module) => module.SIUnsplash),
  },
  {
    prefix: "lg",
    slug: "crunchyroll",
    title: "Crunchyroll",
    hex: "#F47521",
    keywords: ["anime", "streaming", "video"],
    loadIcon: () => import("@icongo/si/esm/SICrunchyroll").then((module) => module.SICrunchyroll),
  },
  {
    prefix: "lg",
    slug: "niconico",
    title: "Niconico",
    hex: "#252525",
    keywords: ["ニコニコ動画", "japan", "video", "streaming"],
    loadIcon: () => import("@icongo/si/esm/SINiconico").then((module) => module.SINiconico),
  },
  {
    prefix: "custom",
    slug: "bilibili",
    title: "Bilibili",
    hex: "#1296DB",
    keywords: ["b站", "哔哩哔哩", "anime", "video", "streaming"],
    loadIcon: () => Promise.resolve(SXBilibili),
  },
  {
    prefix: "lg",
    slug: "kuaishou",
    title: "Kuaishou",
    hex: "#FF4906",
    keywords: ["快手", "short video", "video", "streaming"],
    loadIcon: () => import("@icongo/si/esm/SIKuaishou").then((module) => module.SIKuaishou),
  },
  {
    prefix: "custom",
    slug: "neteasecloudmusic",
    title: "Netease Cloud Music",
    hex: "#DD001B",
    keywords: ["网易云音乐", "netease", "music", "streaming"],
    loadIcon: () => Promise.resolve(SXNeteaseCloudMusic),
  },
  {
    prefix: "lg",
    slug: "youtube",
    title: "YouTube",
    hex: "#FF0000",
    keywords: ["video"],
    loadIcon: () => import("@icongo/lg/esm/LGYoutubeIcon").then((module) => module.LGYoutubeIcon),
  },
  {
    prefix: "lg",
    slug: "spotify",
    title: "Spotify",
    hex: "#1DB954",
    keywords: ["music"],
    loadIcon: () => import("@icongo/lg/esm/LGSpotifyIcon").then((module) => module.LGSpotifyIcon),
  },
  {
    prefix: "lg",
    slug: "netflix",
    title: "Netflix",
    hex: "#E50914",
    keywords: ["video"],
    loadIcon: () => import("@icongo/vl/esm/VLNetflix").then((module) => module.VLNetflix),
  },
  {
    prefix: "lg",
    slug: "amazonprimevideo",
    title: "Amazon Prime Video",
    hex: "#00A8E1",
    keywords: ["amazon", "prime video", "video", "streaming"],
    loadIcon: () => import("@icongo/vl/esm/VLCprime").then((module) => module.VLCprime),
  },
  {
    prefix: "lg",
    slug: "appletvplus",
    title: "Apple TV+",
    hex: "#000000",
    keywords: ["apple tv", "tv+", "streaming", "video"],
    loadIcon: () => import("@icongo/lg/esm/LGApple").then((module) => module.LGApple),
  },
  {
    prefix: "lg",
    slug: "applemusic",
    title: "Apple Music",
    hex: "#FA2D48",
    keywords: ["apple", "music", "streaming"],
    loadIcon: () => import("@icongo/lg/esm/LGApple").then((module) => module.LGApple),
  },
  {
    prefix: "lg",
    slug: "youtubemusic",
    title: "YouTube Music",
    hex: "#FF0000",
    keywords: ["youtube", "music", "streaming"],
    loadIcon: () => import("@icongo/lg/esm/LGYoutubeIcon").then((module) => module.LGYoutubeIcon),
  },
  {
    prefix: "lg",
    slug: "qqmusic",
    title: "QQ Music",
    hex: "#31C27C",
    keywords: ["qq", "qq音乐", "music", "腾讯音乐"],
    loadIcon: () => import("@icongo/vl/esm/VLTencent").then((module) => module.VLTencent),
  },
  {
    prefix: "lg",
    slug: "kugoumusic",
    title: "Kugou Music",
    hex: "#2C78FF",
    keywords: ["酷狗音乐", "kugou", "music", "腾讯音乐"],
    loadIcon: () => import("@icongo/vl/esm/VLTencent").then((module) => module.VLTencent),
  },
  {
    prefix: "lg",
    slug: "kuwomusic",
    title: "Kuwo Music",
    hex: "#F6D128",
    keywords: ["酷我音乐", "kuwo", "music", "腾讯音乐"],
    loadIcon: () => import("@icongo/vl/esm/VLTencent").then((module) => module.VLTencent),
  },
  {
    prefix: "lg",
    slug: "disneyplus",
    title: "Disney+",
    hex: "#113CCF",
    keywords: ["disney", "streaming", "video", "迪士尼+", "流媒体"],
    loadIcon: () => import("@icongo/vl/esm/VLDisney").then((module) => module.VLDisney),
  },
  {
    prefix: "lg",
    slug: "twitch",
    title: "Twitch",
    hex: "#9146FF",
    keywords: ["streaming", "live", "gaming", "直播", "游戏直播"],
    loadIcon: () => import("@icongo/lg/esm/LGTwitch").then((module) => module.LGTwitch),
  },
  {
    prefix: "lg",
    slug: "vimeo",
    title: "Vimeo",
    hex: "#1AB7EA",
    keywords: ["video", "streaming"],
    loadIcon: () => import("@icongo/lg/esm/LGVimeoIcon").then((module) => module.LGVimeoIcon),
  },
  {
    prefix: "lg",
    slug: "soundcloud",
    title: "SoundCloud",
    hex: "#FF5500",
    keywords: ["music", "audio", "streaming", "音乐"],
    loadIcon: () => import("@icongo/lg/esm/LGSoundcloud").then((module) => module.LGSoundcloud),
  },
  {
    prefix: "lg",
    slug: "plex",
    title: "Plex",
    hex: "#E5A00D",
    keywords: ["media server", "streaming", "video"],
    loadIcon: () => import("@icongo/vl/esm/VLPlextv").then((module) => module.VLPlextv),
  },
  {
    prefix: "lg",
    slug: "vlc",
    title: "VLC",
    hex: "#FF8800",
    keywords: ["videolan", "media player", "video", "播放器"],
    loadIcon: () => import("@icongo/vl/esm/VLVideolanVlc").then((module) => module.VLVideolanVlc),
  },
  {
    prefix: "lg",
    slug: "tencentvideo",
    title: "Tencent Video",
    hex: "#0052D9",
    keywords: ["tencent", "qq video", "腾讯视频", "视频", "流媒体"],
    loadIcon: () => import("@icongo/vl/esm/VLTencent").then((module) => module.VLTencent),
  },
  {
    prefix: "lg",
    slug: "weibo",
    title: "Weibo",
    hex: "#E6162D",
    keywords: ["social", "video", "微博", "国内平台"],
    loadIcon: () => import("@icongo/vl/esm/VLWeibo").then((module) => module.VLWeibo),
  },
  {
    prefix: "lg",
    slug: "apple",
    title: "Apple",
    hex: "#000000",
    keywords: ["ios", "mac"],
    loadIcon: () => import("@icongo/lg/esm/LGAppleAppStore").then((module) => module.LGAppleAppStore),
  },
  {
    prefix: "lg",
    slug: "tiktok",
    title: "TikTok",
    hex: "#000000",
    keywords: ["short video"],
    loadIcon: () => import("@icongo/lg/esm/LGTiktokIcon").then((module) => module.LGTiktokIcon),
  },
  {
    prefix: "lg",
    slug: "discord",
    title: "Discord",
    hex: "#5865F2",
    keywords: ["chat"],
    loadIcon: () => import("@icongo/lg/esm/LGDiscordIcon").then((module) => module.LGDiscordIcon),
  },
  {
    prefix: "lg",
    slug: "telegram",
    title: "Telegram",
    hex: "#26A5E4",
    keywords: ["chat"],
    loadIcon: () => import("@icongo/lg/esm/LGTelegram").then((module) => module.LGTelegram),
  },
  {
    prefix: "lg",
    slug: "facebook",
    title: "Facebook",
    hex: "#1877F2",
    keywords: ["social"],
    loadIcon: () => import("@icongo/lg/esm/LGFacebook").then((module) => module.LGFacebook),
  },
  {
    prefix: "lg",
    slug: "instagram",
    title: "Instagram",
    hex: "#E4405F",
    keywords: ["social"],
    loadIcon: () => import("@icongo/lg/esm/LGInstagramIcon").then((module) => module.LGInstagramIcon),
  },
  {
    prefix: "lg",
    slug: "bitcoin",
    title: "Bitcoin",
    hex: "#F7931A",
    keywords: ["btc", "crypto"],
    loadIcon: () => import("@icongo/lg/esm/LGBitcoin").then((module) => module.LGBitcoin),
  },
  {
    prefix: "lg",
    slug: "ethereum",
    title: "Ethereum",
    hex: "#3C3C3D",
    keywords: ["eth", "crypto"],
    loadIcon: () => import("@icongo/lg/esm/LGEthereum").then((module) => module.LGEthereum),
  },
  {
    prefix: "lg",
    slug: "monero",
    title: "Monero",
    hex: "#FF6600",
    keywords: ["xmr", "crypto"],
    loadIcon: () => import("@icongo/lg/esm/LGMonero").then((module) => module.LGMonero),
  },
  {
    prefix: "lg",
    slug: "kraken",
    title: "Kraken",
    hex: "#5741D9",
    keywords: ["exchange", "crypto"],
    loadIcon: () => import("@icongo/lg/esm/LGKraken").then((module) => module.LGKraken),
  },
  {
    prefix: "bl",
    slug: "bankofamerica",
    title: "Bank of America",
    hex: "#E31837",
    keywords: ["bank", "boa"],
    loadIcon: () => import("@icongo/bl/esm/BLBankofamericaRect").then((module) => module.BLBankofamericaRect),
  },
  {
    prefix: "bl",
    slug: "hsbc",
    title: "HSBC",
    hex: "#DB0011",
    keywords: ["bank"],
    loadIcon: () => import("@icongo/bl/esm/BLHsbcRect").then((module) => module.BLHsbcRect),
  },
  {
    prefix: "bl",
    slug: "bankofchina",
    title: "Bank of China",
    hex: "#A3121A",
    keywords: ["boc", "中国银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLBocRect").then((module) => module.BLBocRect),
  },
  {
    prefix: "bl",
    slug: "icbc",
    title: "ICBC",
    hex: "#C8102E",
    keywords: ["工商银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLIcbcRect").then((module) => module.BLIcbcRect),
  },
  {
    prefix: "bl",
    slug: "ccb",
    title: "China Construction Bank",
    hex: "#005BAC",
    keywords: ["建设银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLCcbRect").then((module) => module.BLCcbRect),
  },
  {
    prefix: "bl",
    slug: "abc",
    title: "Agricultural Bank of China",
    hex: "#007D49",
    keywords: ["农业银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLAbchinaRect").then((module) => module.BLAbchinaRect),
  },
  {
    prefix: "bl",
    slug: "cmbchina",
    title: "China Merchants Bank",
    hex: "#D71920",
    keywords: ["招商银行", "cmb", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLCmbchinaRect").then((module) => module.BLCmbchinaRect),
  },
  {
    prefix: "bl",
    slug: "cmbc",
    title: "China Minsheng Bank",
    hex: "#005BAC",
    keywords: ["民生银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLCmbcRect").then((module) => module.BLCmbcRect),
  },
  {
    prefix: "bl",
    slug: "citicbank",
    title: "China CITIC Bank",
    hex: "#D32F2F",
    keywords: ["中信银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLCiticbankRect").then((module) => module.BLCiticbankRect),
  },
  {
    prefix: "bl",
    slug: "bankcomm",
    title: "Bank of Communications",
    hex: "#005BAC",
    keywords: ["交通银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLBankcommRect").then((module) => module.BLBankcommRect),
  },
  {
    prefix: "bl",
    slug: "cebbank",
    title: "China Everbright Bank",
    hex: "#6A9E3B",
    keywords: ["光大银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLCebbankRect").then((module) => module.BLCebbankRect),
  },
  {
    prefix: "bl",
    slug: "cib",
    title: "Industrial Bank",
    hex: "#004098",
    keywords: ["兴业银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLCibRect").then((module) => module.BLCibRect),
  },
]
