import type { ComponentType, SVGProps } from "react"
import {
  SiNetflix, SiNetflixHex,
  SiSpotify, SiSpotifyHex,
  SiGithub, SiGithubHex,
  SiYoutube, SiYoutubeHex,
  SiDiscord, SiDiscordHex,
  SiApple, SiAppleHex,
  SiGoogle, SiGoogleHex,
  SiDropbox, SiDropboxHex,
  SiNotion, SiNotionHex,
  SiFigma, SiFigmaHex,
  SiLinear, SiLinearHex,
  SiVercel, SiVercelHex,
  SiCloudflare, SiCloudflareHex,
  SiDigitalocean, SiDigitaloceanHex,
  SiDocker, SiDockerHex,
  SiGitlab, SiGitlabHex,
  SiBitbucket, SiBitbucketHex,
  SiJira, SiJiraHex,
  SiTrello, SiTrelloHex,
  SiZoom, SiZoomHex,
  SiTwitch, SiTwitchHex,
  SiX, SiXHex,
  SiInstagram, SiInstagramHex,
  SiFacebook, SiFacebookHex,
  SiReddit, SiRedditHex,
  SiTiktok, SiTiktokHex,
  SiPinterest, SiPinterestHex,
  SiWhatsapp, SiWhatsappHex,
  SiTelegram, SiTelegramHex,
  SiPaypal, SiPaypalHex,
  SiStripe, SiStripeHex,
  SiShopify, SiShopifyHex,
  SiWordpress, SiWordpressHex,
  SiSubstack, SiSubstackHex,
  SiPatreon, SiPatreonHex,
  SiSteam, SiSteamHex,
  SiHbo, SiHboHex,
  SiCrunchyroll, SiCrunchyrollHex,
  SiDeezer, SiDeezerHex,
  SiTidal, SiTidalHex,
  SiGoogledrive, SiGoogledriveHex,
  SiIcloud, SiIcloudHex,
  SiEvernote, SiEvernoteHex,
  SiTodoist, SiTodoistHex,
  SiNordvpn, SiNordvpnHex,
  SiSignal, SiSignalHex,
  SiProtonmail, SiProtonmailHex,
  SiBitwarden, SiBitwardenHex,
  SiGrammarly, SiGrammarlyHex,
  SiDuolingo, SiDuolingoHex,
  SiCoursera, SiCourseraHex,
  SiUdemy, SiUdemyHex,
  SiMedium, SiMediumHex,
  SiDribbble, SiDribbbleHex,
  SiBehance, SiBehanceHex,
  SiUnsplash, SiUnsplashHex,
  SiProducthunt, SiProducthuntHex,
  SiStackoverflow, SiStackoverflowHex,
  SiNetlify, SiNetlifyHex,
  SiFirebase, SiFirebaseHex,
  SiSupabase, SiSupabaseHex,
  SiMongodb, SiMongodbHex,
  SiPostgresql, SiPostgresqlHex,
  SiRedis, SiRedisHex,
  SiTailwindcss, SiTailwindcssHex,
  SiReact, SiReactHex,
  SiSvelte, SiSvelteHex,
  SiAngular, SiAngularHex,
  SiPython, SiPythonHex,
  SiRust, SiRustHex,
  SiGo, SiGoHex,
  SiTypescript, SiTypescriptHex,
  SiSwift, SiSwiftHex,
  SiKotlin, SiKotlinHex,
  SiPhp, SiPhpHex,
  SiRuby, SiRubyHex,
  SiNpm, SiNpmHex,
  SiApplemusic, SiApplemusicHex,
  SiAppletv, SiAppletvHex,
  SiParamountplus, SiParamountplusHex,
  SiPlex, SiPlexHex,
  SiJellyfin, SiJellyfinHex,
  SiMubi, SiMubiHex,
  SiTubi, SiTubiHex,
  SiVimeo, SiVimeoHex,
  SiYoutubemusic, SiYoutubemusicHex,
  SiSoundcloud, SiSoundcloudHex,
  SiBandcamp, SiBandcampHex,
  SiAudible, SiAudibleHex,
  SiIheartradio, SiIheartradioHex,
  SiPocketcasts, SiPocketcastsHex,
  SiEpicgames, SiEpicgamesHex,
  SiGogdotcom, SiGogdotcomHex,
  SiItchdotio, SiItchdotioHex,
  SiPlaystation, SiPlaystationHex,
  SiRiotgames, SiRiotgamesHex,
  SiRoblox, SiRobloxHex,
  SiUbisoft, SiUbisoftHex,
  SiLeagueoflegends, SiLeagueoflegendsHex,
  SiSnapchat, SiSnapchatHex,
  SiBluesky, SiBlueskyHex,
  SiMastodon, SiMastodonHex,
  SiThreads, SiThreadsHex,
  SiBuymeacoffee, SiBuymeacoffeeHex,
  SiKofi, SiKofiHex,
  SiLinktree, SiLinktreeHex,
  SiStrava, SiStravaHex,
  SiGarmin, SiGarminHex,
  SiHeadspace, SiHeadspaceHex,
  SiAnki, SiAnkiHex,
  SiQuizlet, SiQuizletHex,
  SiSkillshare, SiSkillshareHex,
  SiOpenrouter, SiOpenrouterHex,
  SiPerplexity, SiPerplexityHex,
  SiAnthropic, SiAnthropicHex,
  SiClaude, SiClaudeHex,
  SiRailway, SiRailwayHex,
  SiRender, SiRenderHex,
  SiFlydotio, SiFlydotioHex,
  SiGooglecloud, SiGooglecloudHex,
  SiWebex, SiWebexHex,
  SiObsidian, SiObsidianHex,
  SiGooglemeet, SiGooglemeetHex,
  SiGoogledocs, SiGoogledocsHex,
  SiGooglesheets, SiGooglesheetsHex,
  SiProtonvpn, SiProtonvpnHex,
  SiMullvad, SiMullvadHex,
  SiExpressvpn, SiExpressvpnHex,
  SiSurfshark, SiSurfsharkHex,
  Si1password, Si1passwordHex,
  SiLastpass, SiLastpassHex,
  SiDashlane, SiDashlaneHex,
  SiKeeper, SiKeeperHex,
  SiGoodreads, SiGoodreadsHex,
  SiInstapaper, SiInstapaperHex,
  SiFeedly, SiFeedlyHex,
  SiDazn, SiDaznHex,
  SiDailymotion, SiDailymotionHex,
  SiKodi, SiKodiHex,
  SiEmby, SiEmbyHex,
  SiNextcloud, SiNextcloudHex,
  SiGrafana, SiGrafanaHex,
  SiDatadog, SiDatadogHex,
  SiSentry, SiSentryHex,
  SiPostman, SiPostmanHex,
  SiInsomnia, SiInsomniaHex,
  SiGitbook, SiGitbookHex,
  SiConfluence, SiConfluenceHex,
  SiCoda, SiCodaHex,
  SiAsana, SiAsanaHex,
  SiClickup, SiClickupHex,
  SiBasecamp, SiBasecampHex,
  SiCoinbase, SiCoinbaseHex,
  SiBinance, SiBinanceHex,
  SiCashapp, SiCashappHex,
  SiPayoneer, SiPayoneerHex,
  SiBlender, SiBlenderHex,
  SiDavinciresolve, SiDavinciresolveHex,
  SiPrometheus, SiPrometheusHex,
  SiPortainer, SiPortainerHex,
  SiHomeassistant, SiHomeassistantHex,
  SiPihole, SiPiholeHex,
  SiAnsible, SiAnsibleHex,
  SiTerraform, SiTerraformHex,
  SiFubo, SiFuboHex,
} from "@icons-pack/react-simple-icons"

export interface BrandIcon {
  slug: string
  title: string
  hex: string
  Icon: ComponentType<SVGProps<SVGSVGElement> & { size?: number | string; color?: string }>
}

export const brandIcons: BrandIcon[] = [
  { slug: "netflix", title: "Netflix", hex: SiNetflixHex, Icon: SiNetflix },
  { slug: "youtube", title: "YouTube", hex: SiYoutubeHex, Icon: SiYoutube },
  { slug: "youtubemusic", title: "YouTube Music", hex: SiYoutubemusicHex, Icon: SiYoutubemusic },
  { slug: "twitch", title: "Twitch", hex: SiTwitchHex, Icon: SiTwitch },
  { slug: "hbo", title: "HBO", hex: SiHboHex, Icon: SiHbo },
  { slug: "paramountplus", title: "Paramount+", hex: SiParamountplusHex, Icon: SiParamountplus },
  { slug: "appletv", title: "Apple TV+", hex: SiAppletvHex, Icon: SiAppletv },
  { slug: "crunchyroll", title: "Crunchyroll", hex: SiCrunchyrollHex, Icon: SiCrunchyroll },
  { slug: "vimeo", title: "Vimeo", hex: SiVimeoHex, Icon: SiVimeo },
  { slug: "plex", title: "Plex", hex: SiPlexHex, Icon: SiPlex },
  { slug: "jellyfin", title: "Jellyfin", hex: SiJellyfinHex, Icon: SiJellyfin },
  { slug: "mubi", title: "MUBI", hex: SiMubiHex, Icon: SiMubi },
  { slug: "tubi", title: "Tubi", hex: SiTubiHex, Icon: SiTubi },
  { slug: "dazn", title: "DAZN", hex: SiDaznHex, Icon: SiDazn },
  { slug: "dailymotion", title: "Dailymotion", hex: SiDailymotionHex, Icon: SiDailymotion },
  { slug: "fubo", title: "Fubo", hex: SiFuboHex, Icon: SiFubo },
  { slug: "kodi", title: "Kodi", hex: SiKodiHex, Icon: SiKodi },
  { slug: "emby", title: "Emby", hex: SiEmbyHex, Icon: SiEmby },
  { slug: "spotify", title: "Spotify", hex: SiSpotifyHex, Icon: SiSpotify },
  { slug: "applemusic", title: "Apple Music", hex: SiApplemusicHex, Icon: SiApplemusic },
  { slug: "deezer", title: "Deezer", hex: SiDeezerHex, Icon: SiDeezer },
  { slug: "tidal", title: "Tidal", hex: SiTidalHex, Icon: SiTidal },
  { slug: "soundcloud", title: "SoundCloud", hex: SiSoundcloudHex, Icon: SiSoundcloud },
  { slug: "bandcamp", title: "Bandcamp", hex: SiBandcampHex, Icon: SiBandcamp },
  { slug: "iheartradio", title: "iHeartRadio", hex: SiIheartradioHex, Icon: SiIheartradio },
  { slug: "pocketcasts", title: "Pocket Casts", hex: SiPocketcastsHex, Icon: SiPocketcasts },
  { slug: "audible", title: "Audible", hex: SiAudibleHex, Icon: SiAudible },
  { slug: "goodreads", title: "Goodreads", hex: SiGoodreadsHex, Icon: SiGoodreads },
  { slug: "instapaper", title: "Instapaper", hex: SiInstapaperHex, Icon: SiInstapaper },
  { slug: "feedly", title: "Feedly", hex: SiFeedlyHex, Icon: SiFeedly },
  { slug: "steam", title: "Steam", hex: SiSteamHex, Icon: SiSteam },
  { slug: "epicgames", title: "Epic Games", hex: SiEpicgamesHex, Icon: SiEpicgames },
  { slug: "gogdotcom", title: "GOG.com", hex: SiGogdotcomHex, Icon: SiGogdotcom },
  { slug: "itchdotio", title: "itch.io", hex: SiItchdotioHex, Icon: SiItchdotio },
  { slug: "playstation", title: "PlayStation", hex: SiPlaystationHex, Icon: SiPlaystation },
  { slug: "riotgames", title: "Riot Games", hex: SiRiotgamesHex, Icon: SiRiotgames },
  { slug: "roblox", title: "Roblox", hex: SiRobloxHex, Icon: SiRoblox },
  { slug: "ubisoft", title: "Ubisoft", hex: SiUbisoftHex, Icon: SiUbisoft },
  { slug: "leagueoflegends", title: "League of Legends", hex: SiLeagueoflegendsHex, Icon: SiLeagueoflegends },
  { slug: "apple", title: "Apple", hex: SiAppleHex, Icon: SiApple },
  { slug: "google", title: "Google", hex: SiGoogleHex, Icon: SiGoogle },
  { slug: "googledrive", title: "Google Drive", hex: SiGoogledriveHex, Icon: SiGoogledrive },
  { slug: "googledocs", title: "Google Docs", hex: SiGoogledocsHex, Icon: SiGoogledocs },
  { slug: "googlesheets", title: "Google Sheets", hex: SiGooglesheetsHex, Icon: SiGooglesheets },
  { slug: "googlemeet", title: "Google Meet", hex: SiGooglemeetHex, Icon: SiGooglemeet },
  { slug: "icloud", title: "iCloud", hex: SiIcloudHex, Icon: SiIcloud },
  { slug: "github", title: "GitHub", hex: SiGithubHex, Icon: SiGithub },
  { slug: "gitlab", title: "GitLab", hex: SiGitlabHex, Icon: SiGitlab },
  { slug: "bitbucket", title: "Bitbucket", hex: SiBitbucketHex, Icon: SiBitbucket },
  { slug: "docker", title: "Docker", hex: SiDockerHex, Icon: SiDocker },
  { slug: "vercel", title: "Vercel", hex: SiVercelHex, Icon: SiVercel },
  { slug: "netlify", title: "Netlify", hex: SiNetlifyHex, Icon: SiNetlify },
  { slug: "cloudflare", title: "Cloudflare", hex: SiCloudflareHex, Icon: SiCloudflare },
  { slug: "digitalocean", title: "DigitalOcean", hex: SiDigitaloceanHex, Icon: SiDigitalocean },
  { slug: "googlecloud", title: "Google Cloud", hex: SiGooglecloudHex, Icon: SiGooglecloud },
  { slug: "railway", title: "Railway", hex: SiRailwayHex, Icon: SiRailway },
  { slug: "render", title: "Render", hex: SiRenderHex, Icon: SiRender },
  { slug: "flydotio", title: "Fly.io", hex: SiFlydotioHex, Icon: SiFlydotio },
  { slug: "firebase", title: "Firebase", hex: SiFirebaseHex, Icon: SiFirebase },
  { slug: "supabase", title: "Supabase", hex: SiSupabaseHex, Icon: SiSupabase },
  { slug: "mongodb", title: "MongoDB", hex: SiMongodbHex, Icon: SiMongodb },
  { slug: "postgresql", title: "PostgreSQL", hex: SiPostgresqlHex, Icon: SiPostgresql },
  { slug: "redis", title: "Redis", hex: SiRedisHex, Icon: SiRedis },
  { slug: "nextcloud", title: "Nextcloud", hex: SiNextcloudHex, Icon: SiNextcloud },
  { slug: "homeassistant", title: "Home Assistant", hex: SiHomeassistantHex, Icon: SiHomeassistant },
  { slug: "pihole", title: "Pi-hole", hex: SiPiholeHex, Icon: SiPihole },
  { slug: "portainer", title: "Portainer", hex: SiPortainerHex, Icon: SiPortainer },
  { slug: "grafana", title: "Grafana", hex: SiGrafanaHex, Icon: SiGrafana },
  { slug: "datadog", title: "Datadog", hex: SiDatadogHex, Icon: SiDatadog },
  { slug: "sentry", title: "Sentry", hex: SiSentryHex, Icon: SiSentry },
  { slug: "prometheus", title: "Prometheus", hex: SiPrometheusHex, Icon: SiPrometheus },
  { slug: "ansible", title: "Ansible", hex: SiAnsibleHex, Icon: SiAnsible },
  { slug: "terraform", title: "Terraform", hex: SiTerraformHex, Icon: SiTerraform },
  { slug: "notion", title: "Notion", hex: SiNotionHex, Icon: SiNotion },
  { slug: "figma", title: "Figma", hex: SiFigmaHex, Icon: SiFigma },
  { slug: "linear", title: "Linear", hex: SiLinearHex, Icon: SiLinear },
  { slug: "jira", title: "Jira", hex: SiJiraHex, Icon: SiJira },
  { slug: "trello", title: "Trello", hex: SiTrelloHex, Icon: SiTrello },
  { slug: "todoist", title: "Todoist", hex: SiTodoistHex, Icon: SiTodoist },
  { slug: "evernote", title: "Evernote", hex: SiEvernoteHex, Icon: SiEvernote },
  { slug: "obsidian", title: "Obsidian", hex: SiObsidianHex, Icon: SiObsidian },
  { slug: "confluence", title: "Confluence", hex: SiConfluenceHex, Icon: SiConfluence },
  { slug: "coda", title: "Coda", hex: SiCodaHex, Icon: SiCoda },
  { slug: "asana", title: "Asana", hex: SiAsanaHex, Icon: SiAsana },
  { slug: "clickup", title: "ClickUp", hex: SiClickupHex, Icon: SiClickup },
  { slug: "basecamp", title: "Basecamp", hex: SiBasecampHex, Icon: SiBasecamp },
  { slug: "gitbook", title: "GitBook", hex: SiGitbookHex, Icon: SiGitbook },
  { slug: "zoom", title: "Zoom", hex: SiZoomHex, Icon: SiZoom },
  { slug: "webex", title: "Webex", hex: SiWebexHex, Icon: SiWebex },
  { slug: "dropbox", title: "Dropbox", hex: SiDropboxHex, Icon: SiDropbox },
  { slug: "postman", title: "Postman", hex: SiPostmanHex, Icon: SiPostman },
  { slug: "insomnia", title: "Insomnia", hex: SiInsomniaHex, Icon: SiInsomnia },
  { slug: "discord", title: "Discord", hex: SiDiscordHex, Icon: SiDiscord },
  { slug: "x", title: "X", hex: SiXHex, Icon: SiX },
  { slug: "instagram", title: "Instagram", hex: SiInstagramHex, Icon: SiInstagram },
  { slug: "facebook", title: "Facebook", hex: SiFacebookHex, Icon: SiFacebook },
  { slug: "reddit", title: "Reddit", hex: SiRedditHex, Icon: SiReddit },
  { slug: "tiktok", title: "TikTok", hex: SiTiktokHex, Icon: SiTiktok },
  { slug: "pinterest", title: "Pinterest", hex: SiPinterestHex, Icon: SiPinterest },
  { slug: "snapchat", title: "Snapchat", hex: SiSnapchatHex, Icon: SiSnapchat },
  { slug: "bluesky", title: "Bluesky", hex: SiBlueskyHex, Icon: SiBluesky },
  { slug: "mastodon", title: "Mastodon", hex: SiMastodonHex, Icon: SiMastodon },
  { slug: "threads", title: "Threads", hex: SiThreadsHex, Icon: SiThreads },
  { slug: "whatsapp", title: "WhatsApp", hex: SiWhatsappHex, Icon: SiWhatsapp },
  { slug: "telegram", title: "Telegram", hex: SiTelegramHex, Icon: SiTelegram },
  { slug: "signal", title: "Signal", hex: SiSignalHex, Icon: SiSignal },
  { slug: "patreon", title: "Patreon", hex: SiPatreonHex, Icon: SiPatreon },
  { slug: "buymeacoffee", title: "Buy Me a Coffee", hex: SiBuymeacoffeeHex, Icon: SiBuymeacoffee },
  { slug: "kofi", title: "Ko-fi", hex: SiKofiHex, Icon: SiKofi },
  { slug: "linktree", title: "Linktree", hex: SiLinktreeHex, Icon: SiLinktree },
  { slug: "substack", title: "Substack", hex: SiSubstackHex, Icon: SiSubstack },
  { slug: "medium", title: "Medium", hex: SiMediumHex, Icon: SiMedium },
  { slug: "paypal", title: "PayPal", hex: SiPaypalHex, Icon: SiPaypal },
  { slug: "stripe", title: "Stripe", hex: SiStripeHex, Icon: SiStripe },
  { slug: "shopify", title: "Shopify", hex: SiShopifyHex, Icon: SiShopify },
  { slug: "coinbase", title: "Coinbase", hex: SiCoinbaseHex, Icon: SiCoinbase },
  { slug: "binance", title: "Binance", hex: SiBinanceHex, Icon: SiBinance },
  { slug: "cashapp", title: "Cash App", hex: SiCashappHex, Icon: SiCashapp },
  { slug: "payoneer", title: "Payoneer", hex: SiPayoneerHex, Icon: SiPayoneer },
  { slug: "wordpress", title: "WordPress", hex: SiWordpressHex, Icon: SiWordpress },
  { slug: "strava", title: "Strava", hex: SiStravaHex, Icon: SiStrava },
  { slug: "garmin", title: "Garmin", hex: SiGarminHex, Icon: SiGarmin },
  { slug: "headspace", title: "Headspace", hex: SiHeadspaceHex, Icon: SiHeadspace },
  { slug: "duolingo", title: "Duolingo", hex: SiDuolingoHex, Icon: SiDuolingo },
  { slug: "coursera", title: "Coursera", hex: SiCourseraHex, Icon: SiCoursera },
  { slug: "udemy", title: "Udemy", hex: SiUdemyHex, Icon: SiUdemy },
  { slug: "skillshare", title: "Skillshare", hex: SiSkillshareHex, Icon: SiSkillshare },
  { slug: "quizlet", title: "Quizlet", hex: SiQuizletHex, Icon: SiQuizlet },
  { slug: "anki", title: "Anki", hex: SiAnkiHex, Icon: SiAnki },
  { slug: "perplexity", title: "Perplexity", hex: SiPerplexityHex, Icon: SiPerplexity },
  { slug: "anthropic", title: "Anthropic", hex: SiAnthropicHex, Icon: SiAnthropic },
  { slug: "claude", title: "Claude", hex: SiClaudeHex, Icon: SiClaude },
  { slug: "openrouter", title: "OpenRouter", hex: SiOpenrouterHex, Icon: SiOpenrouter },
  { slug: "protonmail", title: "Proton Mail", hex: SiProtonmailHex, Icon: SiProtonmail },
  { slug: "protonvpn", title: "Proton VPN", hex: SiProtonvpnHex, Icon: SiProtonvpn },
  { slug: "nordvpn", title: "NordVPN", hex: SiNordvpnHex, Icon: SiNordvpn },
  { slug: "expressvpn", title: "ExpressVPN", hex: SiExpressvpnHex, Icon: SiExpressvpn },
  { slug: "mullvad", title: "Mullvad", hex: SiMullvadHex, Icon: SiMullvad },
  { slug: "surfshark", title: "Surfshark", hex: SiSurfsharkHex, Icon: SiSurfshark },
  { slug: "bitwarden", title: "Bitwarden", hex: SiBitwardenHex, Icon: SiBitwarden },
  { slug: "1password", title: "1Password", hex: Si1passwordHex, Icon: Si1password },
  { slug: "lastpass", title: "LastPass", hex: SiLastpassHex, Icon: SiLastpass },
  { slug: "dashlane", title: "Dashlane", hex: SiDashlaneHex, Icon: SiDashlane },
  { slug: "keeper", title: "Keeper", hex: SiKeeperHex, Icon: SiKeeper },
  { slug: "dribbble", title: "Dribbble", hex: SiDribbbleHex, Icon: SiDribbble },
  { slug: "behance", title: "Behance", hex: SiBehanceHex, Icon: SiBehance },
  { slug: "unsplash", title: "Unsplash", hex: SiUnsplashHex, Icon: SiUnsplash },
  { slug: "blender", title: "Blender", hex: SiBlenderHex, Icon: SiBlender },
  { slug: "davinciresolve", title: "DaVinci Resolve", hex: SiDavinciresolveHex, Icon: SiDavinciresolve },
  { slug: "stackoverflow", title: "Stack Overflow", hex: SiStackoverflowHex, Icon: SiStackoverflow },
  { slug: "producthunt", title: "Product Hunt", hex: SiProducthuntHex, Icon: SiProducthunt },
  { slug: "npm", title: "npm", hex: SiNpmHex, Icon: SiNpm },
  { slug: "grammarly", title: "Grammarly", hex: SiGrammarlyHex, Icon: SiGrammarly },
  { slug: "tailwindcss", title: "Tailwind CSS", hex: SiTailwindcssHex, Icon: SiTailwindcss },
  { slug: "react", title: "React", hex: SiReactHex, Icon: SiReact },
  { slug: "svelte", title: "Svelte", hex: SiSvelteHex, Icon: SiSvelte },
  { slug: "angular", title: "Angular", hex: SiAngularHex, Icon: SiAngular },
  { slug: "typescript", title: "TypeScript", hex: SiTypescriptHex, Icon: SiTypescript },
  { slug: "python", title: "Python", hex: SiPythonHex, Icon: SiPython },
  { slug: "rust", title: "Rust", hex: SiRustHex, Icon: SiRust },
  { slug: "go", title: "Go", hex: SiGoHex, Icon: SiGo },
  { slug: "swift", title: "Swift", hex: SiSwiftHex, Icon: SiSwift },
  { slug: "kotlin", title: "Kotlin", hex: SiKotlinHex, Icon: SiKotlin },
  { slug: "php", title: "PHP", hex: SiPhpHex, Icon: SiPhp },
  { slug: "ruby", title: "Ruby", hex: SiRubyHex, Icon: SiRuby },
]

const brandIconMap = new Map(brandIcons.map((icon) => [icon.slug, icon]))

export function getBrandIcon(slug: string): BrandIcon | undefined {
  return brandIconMap.get(slug)
}
