import type { BrandIconSpec } from "../types"

export const bankBrandSpecs: BrandIconSpec[] = [
  {
    prefix: "bl",
    slug: "bankofamerica",
    title: "Bank of America",
    hex: "#E31837",
    keywords: ["bank", "boa"],
    loadIcon: () => import("@icongo/bl/esm/BLBankofamericaRect").then((module) => module.BLBankofamericaRect),
  },
  {
    prefix: "bl",
    slug: "hsbc",
    title: "HSBC",
    hex: "#DB0011",
    keywords: ["bank"],
    loadIcon: () => import("@icongo/bl/esm/BLHsbcRect").then((module) => module.BLHsbcRect),
  },
  {
    prefix: "bl",
    slug: "bankofchina",
    title: "Bank of China",
    hex: "#A3121A",
    keywords: ["boc", "中国银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLBocRect").then((module) => module.BLBocRect),
  },
  {
    prefix: "bl",
    slug: "icbc",
    title: "ICBC",
    hex: "#C8102E",
    keywords: ["工商银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLIcbcRect").then((module) => module.BLIcbcRect),
  },
  {
    prefix: "bl",
    slug: "ccb",
    title: "China Construction Bank",
    hex: "#005BAC",
    keywords: ["建设银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLCcbRect").then((module) => module.BLCcbRect),
  },
  {
    prefix: "bl",
    slug: "abc",
    title: "Agricultural Bank of China",
    hex: "#007D49",
    keywords: ["农业银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLAbchinaRect").then((module) => module.BLAbchinaRect),
  },
  {
    prefix: "bl",
    slug: "cmbchina",
    title: "China Merchants Bank",
    hex: "#D71920",
    keywords: ["招商银行", "cmb", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLCmbchinaRect").then((module) => module.BLCmbchinaRect),
  },
  {
    prefix: "bl",
    slug: "cmbc",
    title: "China Minsheng Bank",
    hex: "#005BAC",
    keywords: ["民生银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLCmbcRect").then((module) => module.BLCmbcRect),
  },
  {
    prefix: "bl",
    slug: "citicbank",
    title: "China CITIC Bank",
    hex: "#D32F2F",
    keywords: ["中信银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLCiticbankRect").then((module) => module.BLCiticbankRect),
  },
  {
    prefix: "bl",
    slug: "bankcomm",
    title: "Bank of Communications",
    hex: "#005BAC",
    keywords: ["交通银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLBankcommRect").then((module) => module.BLBankcommRect),
  },
  {
    prefix: "bl",
    slug: "cebbank",
    title: "China Everbright Bank",
    hex: "#6A9E3B",
    keywords: ["光大银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLCebbankRect").then((module) => module.BLCebbankRect),
  },
  {
    prefix: "bl",
    slug: "cib",
    title: "Industrial Bank",
    hex: "#004098",
    keywords: ["兴业银行", "bank"],
    loadIcon: () => import("@icongo/bl/esm/BLCibRect").then((module) => module.BLCibRect),
  },
]
