import type { BrandIconSpec } from "../types"

export const coreBrandSpecs: BrandIconSpec[] = [
  {
    prefix: "lg",
    slug: "paypal",
    title: "PayPal",
    hex: "#003087",
    keywords: ["payment"],
    loadIcon: () => import("@icongo/lg/esm/LGPaypal").then((module) => module.LGPaypal),
  },
  {
    prefix: "lg",
    slug: "stripe",
    title: "Stripe",
    hex: "#635BFF",
    keywords: ["payment"],
    loadIcon: () => import("@icongo/lg/esm/LGStripe").then((module) => module.LGStripe),
  },
  {
    prefix: "lg",
    slug: "visa",
    title: "Visa",
    hex: "#1434CB",
    keywords: ["payment", "card"],
    loadIcon: () => import("@icongo/lg/esm/LGVisa").then((module) => module.LGVisa),
  },
  {
    prefix: "lg",
    slug: "mastercard",
    title: "Mastercard",
    hex: "#EB001B",
    keywords: ["payment", "card"],
    loadIcon: () => import("@icongo/lg/esm/LGMastercard").then((module) => module.LGMastercard),
  },
  {
    prefix: "lg",
    slug: "amex",
    title: "American Express",
    hex: "#2E77BC",
    keywords: ["payment", "card", "american express"],
    loadIcon: () => import("@icongo/lg/esm/LGAmex").then((module) => module.LGAmex),
  },
  {
    prefix: "lg",
    slug: "jcb",
    title: "JCB",
    hex: "#0B4EA2",
    keywords: ["payment", "card"],
    loadIcon: () => import("@icongo/lg/esm/LGJcb").then((module) => module.LGJcb),
  },
  {
    prefix: "lg",
    slug: "unionpay",
    title: "UnionPay",
    hex: "#00447C",
    keywords: ["payment", "card", "银联"],
    loadIcon: () => import("@icongo/lg/esm/LGUnionpay").then((module) => module.LGUnionpay),
  },
  {
    prefix: "lg",
    slug: "applepay",
    title: "Apple Pay",
    hex: "#000000",
    keywords: ["payment", "wallet"],
    loadIcon: () => import("@icongo/lg/esm/LGApplePay").then((module) => module.LGApplePay),
  },
  {
    prefix: "lg",
    slug: "googlepay",
    title: "Google Pay",
    hex: "#4285F4",
    keywords: ["payment", "wallet"],
    loadIcon: () => import("@icongo/lg/esm/LGGooglePayIcon").then((module) => module.LGGooglePayIcon),
  },
  {
    prefix: "lg",
    slug: "openai",
    title: "OpenAI",
    hex: "#412991",
    keywords: ["chatgpt", "gpt", "ai"],
    loadIcon: () => import("@icongo/lg/esm/LGOpenaiIcon").then((module) => module.LGOpenaiIcon),
  },
  {
    prefix: "lg",
    slug: "google",
    title: "Google",
    hex: "#4285F4",
    keywords: ["search", "workspace"],
    loadIcon: () => import("@icongo/lg/esm/LGGoogleIcon").then((module) => module.LGGoogleIcon),
  },
  {
    prefix: "lg",
    slug: "googlecloud",
    title: "Google Cloud",
    hex: "#4285F4",
    keywords: ["gcp", "cloud"],
    loadIcon: () => import("@icongo/lg/esm/LGGoogleCloud").then((module) => module.LGGoogleCloud),
  },
  {
    prefix: "lg",
    slug: "cloudflare",
    title: "Cloudflare",
    hex: "#F38020",
    keywords: ["cloud", "cdn"],
    loadIcon: () => import("@icongo/lg/esm/LGCloudflare").then((module) => module.LGCloudflare),
  },
  {
    prefix: "lg",
    slug: "digitalocean",
    title: "DigitalOcean",
    hex: "#0080FF",
    keywords: ["cloud"],
    loadIcon: () => import("@icongo/vl/esm/VLDigitalocean").then((module) => module.VLDigitalocean),
  },
  {
    prefix: "lg",
    slug: "vercel",
    title: "Vercel",
    hex: "#000000",
    keywords: ["hosting"],
    loadIcon: () => import("@icongo/lg/esm/LGVercelIcon").then((module) => module.LGVercelIcon),
  },
  {
    prefix: "lg",
    slug: "netlify",
    title: "Netlify",
    hex: "#00C7B7",
    keywords: ["hosting"],
    loadIcon: () => import("@icongo/lg/esm/LGNetlify").then((module) => module.LGNetlify),
  },
  {
    prefix: "lg",
    slug: "aws",
    title: "AWS",
    hex: "#FF9900",
    keywords: ["amazon cloud", "cloud"],
    loadIcon: () => import("@icongo/lg/esm/LGAws").then((module) => module.LGAws),
  },
  {
    prefix: "lg",
    slug: "oracle",
    title: "Oracle",
    hex: "#F80000",
    keywords: ["cloud"],
    loadIcon: () => import("@icongo/vl/esm/VLOracle").then((module) => module.VLOracle),
  },
  {
    prefix: "lg",
    slug: "ibm",
    title: "IBM",
    hex: "#1261FE",
    keywords: ["cloud"],
    loadIcon: () => import("@icongo/lg/esm/LGIbm").then((module) => module.LGIbm),
  },
  {
    prefix: "lg",
    slug: "namecheap",
    title: "Namecheap",
    hex: "#FF6A00",
    keywords: ["domain"],
    loadIcon: () => import("@icongo/lg/esm/LGNamecheap").then((module) => module.LGNamecheap),
  },
  {
    prefix: "lg",
    slug: "github",
    title: "GitHub",
    hex: "#181717",
    keywords: ["code", "git"],
    loadIcon: () => import("@icongo/lg/esm/LGGithubIcon").then((module) => module.LGGithubIcon),
  },
  {
    prefix: "lg",
    slug: "gitlab",
    title: "GitLab",
    hex: "#FC6D26",
    keywords: ["code", "git"],
    loadIcon: () => import("@icongo/lg/esm/LGGitlab").then((module) => module.LGGitlab),
  },
  {
    prefix: "lg",
    slug: "docker",
    title: "Docker",
    hex: "#2496ED",
    keywords: ["container"],
    loadIcon: () => import("@icongo/lg/esm/LGDockerIcon").then((module) => module.LGDockerIcon),
  },
  {
    prefix: "lg",
    slug: "figma",
    title: "Figma",
    hex: "#A259FF",
    keywords: ["design"],
    loadIcon: () => import("@icongo/lg/esm/LGFigma").then((module) => module.LGFigma),
  },
  {
    prefix: "lg",
    slug: "postman",
    title: "Postman",
    hex: "#FF6C37",
    keywords: ["api"],
    loadIcon: () => import("@icongo/lg/esm/LGPostmanIcon").then((module) => module.LGPostmanIcon),
  },
  {
    prefix: "lg",
    slug: "insomnia",
    title: "Insomnia",
    hex: "#4000BF",
    keywords: ["api"],
    loadIcon: () => import("@icongo/lg/esm/LGInsomnia").then((module) => module.LGInsomnia),
  },
  {
    prefix: "lg",
    slug: "jira",
    title: "Jira",
    hex: "#0052CC",
    keywords: ["project"],
    loadIcon: () => import("@icongo/lg/esm/LGJira").then((module) => module.LGJira),
  },
  {
    prefix: "lg",
    slug: "trello",
    title: "Trello",
    hex: "#0052CC",
    keywords: ["project"],
    loadIcon: () => import("@icongo/lg/esm/LGTrello").then((module) => module.LGTrello),
  },
  {
    prefix: "lg",
    slug: "asana",
    title: "Asana",
    hex: "#F06A6A",
    keywords: ["project"],
    loadIcon: () => import("@icongo/lg/esm/LGAsanaIcon").then((module) => module.LGAsanaIcon),
  },
]
