import { SXAlipay } from "../custom/alipay"
import { SXAnthropic } from "../custom/anthropic"
import { SXClaude } from "../custom/claude"
import { SXDeepseek } from "../custom/deepseek"
import { SXEmail } from "../custom/email"
import { SXGemini } from "../custom/gemini"
import { SXGrok } from "../custom/grok"
import { SXHuggingFace } from "../custom/huggingface"
import { SXKimi } from "../custom/kimi"
import { SXMicrosoft365 } from "../custom/microsoft365"
import { SXMistral } from "../custom/mistral"
import { SXNewapi } from "../custom/newapi"
import { SXPerplexity } from "../custom/perplexity"
import { SXQwen } from "../custom/qwen"
import { SXServer } from "../custom/server"
import { SXVpn } from "../custom/vpn"
import { SXWechatPay } from "../custom/wechatpay"
import { SXZhipu } from "../custom/zhipu"

import type { BrandIconSpec } from "../types"

export const coreBrandSpecs: BrandIconSpec[] = [
  {
    prefix: "lg",
    slug: "paypal",
    title: "PayPal",
    hex: "#003087",
    keywords: ["payment"],
    loadIcon: () => import("@icongo/lg/esm/LGPaypal").then((module) => module.LGPaypal),
  },
  {
    prefix: "lg",
    slug: "stripe",
    title: "Stripe",
    hex: "#635BFF",
    keywords: ["payment"],
    loadIcon: () => import("@icongo/lg/esm/LGStripe").then((module) => module.LGStripe),
  },
  {
    prefix: "lg",
    slug: "visa",
    title: "Visa",
    hex: "#1434CB",
    keywords: ["payment", "card"],
    loadIcon: () => import("@icongo/lg/esm/LGVisa").then((module) => module.LGVisa),
  },
  {
    prefix: "lg",
    slug: "mastercard",
    title: "Mastercard",
    hex: "#EB001B",
    keywords: ["payment", "card"],
    loadIcon: () => import("@icongo/lg/esm/LGMastercard").then((module) => module.LGMastercard),
  },
  {
    prefix: "lg",
    slug: "amex",
    title: "American Express",
    hex: "#2E77BC",
    keywords: ["payment", "card", "american express"],
    loadIcon: () => import("@icongo/lg/esm/LGAmex").then((module) => module.LGAmex),
  },
  {
    prefix: "lg",
    slug: "jcb",
    title: "JCB",
    hex: "#0B4EA2",
    keywords: ["payment", "card"],
    loadIcon: () => import("@icongo/lg/esm/LGJcb").then((module) => module.LGJcb),
  },
  {
    prefix: "lg",
    slug: "unionpay",
    title: "UnionPay",
    hex: "#00447C",
    keywords: ["payment", "card", "银联"],
    loadIcon: () => import("@icongo/lg/esm/LGUnionpay").then((module) => module.LGUnionpay),
  },
  {
    prefix: "lg",
    slug: "applepay",
    title: "Apple Pay",
    hex: "#000000",
    keywords: ["payment", "wallet"],
    loadIcon: () => import("@icongo/lg/esm/LGApplePay").then((module) => module.LGApplePay),
  },
  {
    prefix: "lg",
    slug: "googlepay",
    title: "Google Pay",
    hex: "#4285F4",
    keywords: ["payment", "wallet"],
    loadIcon: () => import("@icongo/lg/esm/LGGooglePayIcon").then((module) => module.LGGooglePayIcon),
  },
  {
    prefix: "lg",
    slug: "googleplay",
    title: "Google Play",
    hex: "#34A853",
    keywords: ["app store", "android", "google"],
    loadIcon: () => import("@icongo/vl/esm/VLGooglePlay").then((module) => module.VLGooglePlay),
  },
  {
    prefix: "custom",
    slug: "alipay",
    title: "Alipay",
    hex: "#3988FF",
    keywords: ["payment", "wallet", "支付宝"],
    loadIcon: () => Promise.resolve(SXAlipay),
  },
  {
    prefix: "custom",
    slug: "wechatpay",
    title: "WeChat Pay",
    hex: "#15BA11",
    keywords: ["payment", "wallet", "微信支付"],
    loadIcon: () => Promise.resolve(SXWechatPay),
  },
  {
    prefix: "lg",
    slug: "openai",
    title: "OpenAI / ChatGPT",
    hex: "#412991",
    keywords: ["chatgpt", "gpt", "ai"],
    loadIcon: () => import("@icongo/lg/esm/LGOpenaiIcon").then((module) => module.LGOpenaiIcon),
  },
  {
    prefix: "custom",
    slug: "anthropic",
    title: "Anthropic",
    hex: "#191919",
    keywords: ["ai", "llm", "claude"],
    loadIcon: () => Promise.resolve(SXAnthropic),
  },
  {
    prefix: "custom",
    slug: "claude",
    title: "Claude",
    hex: "#D97757",
    keywords: ["anthropic", "ai", "llm"],
    loadIcon: () => Promise.resolve(SXClaude),
  },
  {
    prefix: "custom",
    slug: "gemini",
    title: "Gemini",
    hex: "#448AFF",
    keywords: ["google", "ai", "llm"],
    loadIcon: () => Promise.resolve(SXGemini),
  },
  {
    prefix: "custom",
    slug: "newapi",
    title: "NewAPI",
    hex: "#5BA8F4",
    keywords: ["api", "gateway", "ai"],
    loadIcon: () => Promise.resolve(SXNewapi),
  },
  {
    prefix: "custom",
    slug: "grok",
    title: "Grok",
    hex: "#000000",
    keywords: ["xai", "ai", "llm"],
    loadIcon: () => Promise.resolve(SXGrok),
  },
  {
    prefix: "custom",
    slug: "mistral",
    title: "Mistral",
    hex: "#F7D046",
    keywords: ["mistral ai", "ai", "llm"],
    loadIcon: () => Promise.resolve(SXMistral),
  },
  {
    prefix: "custom",
    slug: "perplexity",
    title: "Perplexity",
    hex: "#111111",
    keywords: ["ai", "search", "llm"],
    loadIcon: () => Promise.resolve(SXPerplexity),
  },
  {
    prefix: "custom",
    slug: "kimi",
    title: "Kimi",
    hex: "#027AFF",
    keywords: ["moonshot", "ai", "llm"],
    loadIcon: () => Promise.resolve(SXKimi),
  },
  {
    prefix: "custom",
    slug: "zhipu",
    title: "Zhipu",
    hex: "#6253FF",
    keywords: ["智谱", "ai", "llm"],
    loadIcon: () => Promise.resolve(SXZhipu),
  },
  {
    prefix: "custom",
    slug: "qwen",
    title: "Qwen",
    hex: "#615CED",
    keywords: ["通义千问", "ai", "llm"],
    loadIcon: () => Promise.resolve(SXQwen),
  },
  {
    prefix: "custom",
    slug: "deepseek",
    title: "DeepSeek",
    hex: "#4D6BFE",
    keywords: ["deepseek", "ai", "llm"],
    loadIcon: () => Promise.resolve(SXDeepseek),
  },
  {
    prefix: "custom",
    slug: "huggingface",
    title: "Hugging Face",
    hex: "#FFCC4D",
    keywords: ["model hub", "ai", "ml"],
    loadIcon: () => Promise.resolve(SXHuggingFace),
  },
  {
    prefix: "lg",
    slug: "google",
    title: "Google",
    hex: "#4285F4",
    keywords: ["search", "workspace"],
    loadIcon: () => import("@icongo/lg/esm/LGGoogleIcon").then((module) => module.LGGoogleIcon),
  },
  {
    prefix: "lg",
    slug: "googlecloud",
    title: "Google Cloud",
    hex: "#4285F4",
    keywords: ["gcp", "cloud"],
    loadIcon: () => import("@icongo/lg/esm/LGGoogleCloud").then((module) => module.LGGoogleCloud),
  },
  {
    prefix: "lg",
    slug: "cloudflare",
    title: "Cloudflare",
    hex: "#F38020",
    keywords: ["cloud", "cdn"],
    loadIcon: () => import("@icongo/lg/esm/LGCloudflare").then((module) => module.LGCloudflare),
  },
  {
    prefix: "lg",
    slug: "digitalocean",
    title: "DigitalOcean",
    hex: "#0080FF",
    keywords: ["cloud"],
    loadIcon: () => import("@icongo/vl/esm/VLDigitalocean").then((module) => module.VLDigitalocean),
  },
  {
    prefix: "lg",
    slug: "vercel",
    title: "Vercel",
    hex: "#000000",
    keywords: ["hosting"],
    loadIcon: () => import("@icongo/lg/esm/LGVercelIcon").then((module) => module.LGVercelIcon),
  },
  {
    prefix: "lg",
    slug: "netlify",
    title: "Netlify",
    hex: "#00C7B7",
    keywords: ["hosting"],
    loadIcon: () => import("@icongo/lg/esm/LGNetlify").then((module) => module.LGNetlify),
  },
  {
    prefix: "lg",
    slug: "aws",
    title: "AWS",
    hex: "#FF9900",
    keywords: ["amazon cloud", "cloud"],
    loadIcon: () => import("@icongo/lg/esm/LGAws").then((module) => module.LGAws),
  },
  {
    prefix: "lg",
    slug: "oracle",
    title: "Oracle",
    hex: "#F80000",
    keywords: ["cloud"],
    loadIcon: () => import("@icongo/vl/esm/VLOracle").then((module) => module.VLOracle),
  },
  {
    prefix: "lg",
    slug: "ibm",
    title: "IBM",
    hex: "#1261FE",
    keywords: ["cloud"],
    loadIcon: () => import("@icongo/lg/esm/LGIbm").then((module) => module.LGIbm),
  },
  {
    prefix: "lg",
    slug: "namecheap",
    title: "Namecheap",
    hex: "#FF6A00",
    keywords: ["domain"],
    loadIcon: () => import("@icongo/lg/esm/LGNamecheap").then((module) => module.LGNamecheap),
  },
  {
    prefix: "lg",
    slug: "github",
    title: "GitHub",
    hex: "#181717",
    keywords: ["code", "git"],
    loadIcon: () => import("@icongo/lg/esm/LGGithubIcon").then((module) => module.LGGithubIcon),
  },
  {
    prefix: "lg",
    slug: "gitlab",
    title: "GitLab",
    hex: "#FC6D26",
    keywords: ["code", "git"],
    loadIcon: () => import("@icongo/lg/esm/LGGitlab").then((module) => module.LGGitlab),
  },
  {
    prefix: "lg",
    slug: "docker",
    title: "Docker",
    hex: "#2496ED",
    keywords: ["container"],
    loadIcon: () => import("@icongo/lg/esm/LGDockerIcon").then((module) => module.LGDockerIcon),
  },
  {
    prefix: "lg",
    slug: "figma",
    title: "Figma",
    hex: "#A259FF",
    keywords: ["design"],
    loadIcon: () => import("@icongo/lg/esm/LGFigma").then((module) => module.LGFigma),
  },
  {
    prefix: "lg",
    slug: "postman",
    title: "Postman",
    hex: "#FF6C37",
    keywords: ["api"],
    loadIcon: () => import("@icongo/lg/esm/LGPostmanIcon").then((module) => module.LGPostmanIcon),
  },
  {
    prefix: "lg",
    slug: "insomnia",
    title: "Insomnia",
    hex: "#4000BF",
    keywords: ["api"],
    loadIcon: () => import("@icongo/lg/esm/LGInsomnia").then((module) => module.LGInsomnia),
  },
  {
    prefix: "lg",
    slug: "jira",
    title: "Jira",
    hex: "#0052CC",
    keywords: ["project"],
    loadIcon: () => import("@icongo/lg/esm/LGJira").then((module) => module.LGJira),
  },
  {
    prefix: "lg",
    slug: "trello",
    title: "Trello",
    hex: "#0052CC",
    keywords: ["project"],
    loadIcon: () => import("@icongo/lg/esm/LGTrello").then((module) => module.LGTrello),
  },
  {
    prefix: "lg",
    slug: "asana",
    title: "Asana",
    hex: "#F06A6A",
    keywords: ["project"],
    loadIcon: () => import("@icongo/lg/esm/LGAsanaIcon").then((module) => module.LGAsanaIcon),
  },
  {
    prefix: "lg",
    slug: "adguard",
    title: "AdGuard",
    hex: "#68BC71",
    keywords: ["ad blocker", "privacy", "security"],
    loadIcon: () => import("@icongo/vl/esm/VLAdguard").then((module) => module.VLAdguard),
  },
  {
    prefix: "lg",
    slug: "alibabacloud",
    title: "Alibaba Cloud",
    hex: "#FF6A00",
    keywords: ["aliyun", "cloud"],
    loadIcon: () => import("@icongo/vl/esm/VLAlibabacloud").then((module) => module.VLAlibabacloud),
  },
  {
    prefix: "lg",
    slug: "alpinelinux",
    title: "Alpine Linux",
    hex: "#0D597F",
    keywords: ["linux", "os"],
    loadIcon: () => import("@icongo/vl/esm/VLAlpinelinux").then((module) => module.VLAlpinelinux),
  },
  {
    prefix: "lg",
    slug: "android",
    title: "Android",
    hex: "#3DDC84",
    keywords: ["google", "mobile", "os"],
    loadIcon: () => import("@icongo/vl/esm/VLAndroid").then((module) => module.VLAndroid),
  },
  {
    prefix: "lg",
    slug: "archlinux",
    title: "Arch Linux",
    hex: "#1793D1",
    keywords: ["linux", "os"],
    loadIcon: () => import("@icongo/vl/esm/VLArchlinux").then((module) => module.VLArchlinux),
  },
  {
    prefix: "lg",
    slug: "baidu",
    title: "Baidu",
    hex: "#2319DC",
    keywords: ["search", "china"],
    loadIcon: () => import("@icongo/vl/esm/VLBaidu").then((module) => module.VLBaidu),
  },
  {
    prefix: "lg",
    slug: "bitbucket",
    title: "Bitbucket",
    hex: "#0052CC",
    keywords: ["code", "git"],
    loadIcon: () => import("@icongo/lg/esm/LGBitbucket").then((module) => module.LGBitbucket),
  },
  {
    prefix: "lg",
    slug: "browserstack",
    title: "BrowserStack",
    hex: "#FF6F00",
    keywords: ["testing", "browser"],
    loadIcon: () => import("@icongo/lg/esm/LGBrowserstack").then((module) => module.LGBrowserstack),
  },
  {
    prefix: "lg",
    slug: "centos",
    title: "CentOS",
    hex: "#932279",
    keywords: ["linux", "os"],
    loadIcon: () => import("@icongo/vl/esm/VLCentos").then((module) => module.VLCentos),
  },
  {
    prefix: "lg",
    slug: "cloudboostio",
    title: "Cloudboost",
    hex: "#0050FF",
    keywords: ["cloud", "database"],
    loadIcon: () => import("@icongo/vl/esm/VLCloudboostio").then((module) => module.VLCloudboostio),
  },
  {
    prefix: "lg",
    slug: "debian",
    title: "Debian",
    hex: "#A81D33",
    keywords: ["linux", "os"],
    loadIcon: () => import("@icongo/vl/esm/VLDebian").then((module) => module.VLDebian),
  },
  {
    prefix: "lg",
    slug: "email",
    title: "Email",
    hex: "#4A4A4A",
    keywords: ["mail", "inbox"],
    loadIcon: () => Promise.resolve(SXEmail),
  },
  {
    prefix: "lg",
    slug: "elsevier",
    title: "Elsevier",
    hex: "#FF6F00",
    keywords: ["research", "journal", "publisher"],
    loadIcon: () => import("@icongo/vl/esm/VLElsevier").then((module) => module.VLElsevier),
  },
  {
    prefix: "lg",
    slug: "fedora",
    title: "Fedora",
    hex: "#51A2DA",
    keywords: ["linux", "os"],
    loadIcon: () => import("@icongo/vl/esm/VLGetfedora").then((module) => module.VLGetfedora),
  },
  {
    prefix: "lg",
    slug: "googledrive",
    title: "Google Drive",
    hex: "#0F9D58",
    keywords: ["google", "cloud storage"],
    loadIcon: () => import("@icongo/vl/esm/VLGoogleDrive").then((module) => module.VLGoogleDrive),
  },
  {
    prefix: "lg",
    slug: "googlephotos",
    title: "Google Photos",
    hex: "#EA4335",
    keywords: ["google", "photos", "storage"],
    loadIcon: () => import("@icongo/lg/esm/LGGooglePhotos").then((module) => module.LGGooglePhotos),
  },
  {
    prefix: "lg",
    slug: "huawei",
    title: "Huawei",
    hex: "#FF0000",
    keywords: ["cloud", "hardware"],
    loadIcon: () => import("@icongo/vl/esm/VLHuawei").then((module) => module.VLHuawei),
  },
  {
    prefix: "lg",
    slug: "intel",
    title: "Intel",
    hex: "#0071C5",
    keywords: ["chip", "hardware", "cpu"],
    loadIcon: () => import("@icongo/vl/esm/VLIntel").then((module) => module.VLIntel),
  },
  {
    prefix: "lg",
    slug: "kubernetes",
    title: "Kubernetes",
    hex: "#326CE5",
    keywords: ["container", "orchestration"],
    loadIcon: () => import("@icongo/vl/esm/VLKubernetes").then((module) => module.VLKubernetes),
  },
  {
    prefix: "lg",
    slug: "linux",
    title: "Linux",
    hex: "#FCC624",
    keywords: ["linux", "os"],
    loadIcon: () => import("@icongo/vl/esm/VLLinux").then((module) => module.VLLinux),
  },
  {
    prefix: "lg",
    slug: "manjaro",
    title: "Manjaro",
    hex: "#35BF5C",
    keywords: ["linux", "os"],
    loadIcon: () => import("@icongo/lg/esm/LGManjaro").then((module) => module.LGManjaro),
  },
  {
    prefix: "lg",
    slug: "microsoft",
    title: "Microsoft",
    hex: "#00A4EF",
    keywords: ["cloud", "productivity"],
    loadIcon: () => import("@icongo/vl/esm/VLMicrosoft").then((module) => module.VLMicrosoft),
  },
  {
    prefix: "custom",
    slug: "microsoft365",
    title: "Microsoft Office 365",
    hex: "#0078D4",
    keywords: ["office", "microsoft", "productivity"],
    loadIcon: () => Promise.resolve(SXMicrosoft365),
  },
  {
    prefix: "lg",
    slug: "azure",
    title: "Microsoft Azure",
    hex: "#0078D4",
    keywords: ["microsoft", "cloud"],
    loadIcon: () => import("@icongo/lg/esm/LGMicrosoftAzure").then((module) => module.LGMicrosoftAzure),
  },
  {
    prefix: "lg",
    slug: "windows",
    title: "Microsoft Windows",
    hex: "#0078D4",
    keywords: ["microsoft", "os"],
    loadIcon: () => import("@icongo/lg/esm/LGMicrosoftWindows").then((module) => module.LGMicrosoftWindows),
  },
  {
    prefix: "lg",
    slug: "onedrive",
    title: "OneDrive",
    hex: "#0078D4",
    keywords: ["microsoft", "cloud storage"],
    loadIcon: () => import("@icongo/lg/esm/LGMicrosoftOnedrive").then((module) => module.LGMicrosoftOnedrive),
  },
  {
    prefix: "lg",
    slug: "mongodb",
    title: "MongoDB",
    hex: "#47A248",
    keywords: ["database", "nosql"],
    loadIcon: () => import("@icongo/lg/esm/LGMongodbIcon").then((module) => module.LGMongodbIcon),
  },
  {
    prefix: "lg",
    slug: "nextcloud",
    title: "Nextcloud",
    hex: "#0082C9",
    keywords: ["cloud storage", "self-hosted"],
    loadIcon: () => import("@icongo/vl/esm/VLNextcloud").then((module) => module.VLNextcloud),
  },
  {
    prefix: "lg",
    slug: "nvidia",
    title: "NVIDIA",
    hex: "#76B900",
    keywords: ["gpu", "hardware", "ai"],
    loadIcon: () => import("@icongo/vl/esm/VLNvidia").then((module) => module.VLNvidia),
  },
  {
    prefix: "lg",
    slug: "raspberrypi",
    title: "Raspberry Pi",
    hex: "#C51A4A",
    keywords: ["hardware", "linux", "iot"],
    loadIcon: () => import("@icongo/vl/esm/VLRaspberrypi").then((module) => module.VLRaspberrypi),
  },
  {
    prefix: "lg",
    slug: "server",
    title: "Server",
    hex: "#4A4A4A",
    keywords: ["host", "infrastructure"],
    loadIcon: () => Promise.resolve(SXServer),
  },
  {
    prefix: "lg",
    slug: "shopify",
    title: "Shopify",
    hex: "#96BF48",
    keywords: ["ecommerce", "store"],
    loadIcon: () => import("@icongo/vl/esm/VLShopify").then((module) => module.VLShopify),
  },
  {
    prefix: "lg",
    slug: "stackoverflow",
    title: "Stack Overflow",
    hex: "#F58025",
    keywords: ["developer", "community", "q&a"],
    loadIcon: () => import("@icongo/lg/esm/LGStackoverflowIcon").then((module) => module.LGStackoverflowIcon),
  },
  {
    prefix: "lg",
    slug: "supabase",
    title: "Supabase",
    hex: "#3ECF8E",
    keywords: ["database", "backend"],
    loadIcon: () => import("@icongo/vl/esm/VLSupabase").then((module) => module.VLSupabase),
  },
  {
    prefix: "lg",
    slug: "termius",
    title: "Termius",
    hex: "#2B2B2B",
    keywords: ["terminal", "ssh"],
    loadIcon: () => import("@icongo/lg/esm/LGTerminal").then((module) => module.LGTerminal),
  },
  {
    prefix: "lg",
    slug: "unity",
    title: "Unity",
    hex: "#000000",
    keywords: ["game engine", "development"],
    loadIcon: () => import("@icongo/lg/esm/LGUnity").then((module) => module.LGUnity),
  },
  {
    prefix: "lg",
    slug: "ubuntu",
    title: "Ubuntu",
    hex: "#E95420",
    keywords: ["linux", "os"],
    loadIcon: () => import("@icongo/vl/esm/VLUbuntu").then((module) => module.VLUbuntu),
  },
  {
    prefix: "lg",
    slug: "visualstudio",
    title: "Visual Studio",
    hex: "#5C2D91",
    keywords: ["ide", "development"],
    loadIcon: () => import("@icongo/lg/esm/LGVisualStudio").then((module) => module.LGVisualStudio),
  },
  {
    prefix: "lg",
    slug: "vpn",
    title: "VPN",
    hex: "#4A4A4A",
    keywords: ["privacy", "security", "network"],
    loadIcon: () => Promise.resolve(SXVpn),
  },
  {
    prefix: "lg",
    slug: "whatsapp",
    title: "WhatsApp",
    hex: "#25D366",
    keywords: ["chat", "messaging"],
    loadIcon: () => import("@icongo/lg/esm/LGWhatsappIcon").then((module) => module.LGWhatsappIcon),
  },
  {
    prefix: "lg",
    slug: "wordpress",
    title: "WordPress",
    hex: "#21759B",
    keywords: ["cms", "blog"],
    loadIcon: () => import("@icongo/lg/esm/LGWordpressIconAlt").then((module) => module.LGWordpressIconAlt),
  },
]
