import { SXBilibili } from "../custom/bilibili"
import { SXBinance } from "../custom/binance"
import { SXChinaBroadcast } from "../custom/chinabroadcast"
import { SXChinaMobile } from "../custom/chinamobile"
import { SXChinaTelecom } from "../custom/chinatelecom"
import { SXChinaUnicom } from "../custom/chinaunicom"
import { SXDlsite } from "../custom/dlsite"
import { SXEmby } from "../custom/emby"
import { SXGame } from "../custom/game"
import { SXInfuse } from "../custom/infuse"
import { SXIqiyi } from "../custom/iqiyi"
import { SXJellyfin } from "../custom/jellyfin"
import { SXKugouMusic } from "../custom/kugoumusic"
import { SXNeteaseCloudMusic } from "../custom/neteasecloudmusic"
import { SXNeteaseUu } from "../custom/neteaseuu"
import { SXNintendo } from "../custom/nintendo"
import { SXOkx } from "../custom/okx"
import { SXQq } from "../custom/qq"
import { SXQqMusic } from "../custom/qqmusic"
import { SXTencentVideo } from "../custom/tencentvideo"
import { SXXimalaya } from "../custom/ximalaya"
import { SXYoutubeMusic } from "../custom/youtubemusic"

import type { BrandIconSpec } from "../types"

export const entertainmentBrandSpecs: BrandIconSpec[] = [
  {
    prefix: "lg",
    slug: "audible",
    title: "Audible",
    hex: "#F7991C",
    keywords: ["audiobook", "audio", "amazon"],
    loadIcon: () => import("@icongo/si/esm/SIAudible").then((module) => module.SIAudible),
  },
  {
    prefix: "lg",
    slug: "bitly",
    title: "Bitly",
    hex: "#EE6123",
    keywords: ["link shortener", "url", "marketing"],
    loadIcon: () => import("@icongo/si/esm/SIBitly").then((module) => module.SIBitly),
  },
  {
    prefix: "lg",
    slug: "cashapp",
    title: "Cash App",
    hex: "#00D632",
    keywords: ["payment", "wallet", "finance"],
    loadIcon: () => import("@icongo/si/esm/SICashapp").then((module) => module.SICashapp),
  },
  {
    prefix: "lg",
    slug: "chase",
    title: "Chase",
    hex: "#117ACA",
    keywords: ["bank", "payment", "finance"],
    loadIcon: () => import("@icongo/si/esm/SIChase").then((module) => module.SIChase),
  },
  {
    prefix: "lg",
    slug: "dhl",
    title: "DHL",
    hex: "#D40511",
    keywords: ["shipping", "logistics", "delivery"],
    loadIcon: () => import("@icongo/si/esm/SIDhl").then((module) => module.SIDhl),
  },
  {
    prefix: "lg",
    slug: "duolingo",
    title: "Duolingo",
    hex: "#58CC02",
    keywords: ["language", "learning", "education"],
    loadIcon: () => import("@icongo/si/esm/SIDuolingo").then((module) => module.SIDuolingo),
  },
  {
    prefix: "lg",
    slug: "epicgames",
    title: "Epic Games",
    hex: "#313131",
    keywords: ["gaming", "games", "store"],
    loadIcon: () => import("@icongo/si/esm/SIEpicgames").then((module) => module.SIEpicgames),
  },
  {
    prefix: "lg",
    slug: "hbomax",
    title: "HBO Max",
    hex: "#5822B4",
    keywords: ["hbo", "max", "streaming", "video"],
    loadIcon: () => import("@icongo/si/esm/SIHbo").then((module) => module.SIHbo),
  },
  {
    prefix: "lg",
    slug: "max",
    title: "Max",
    hex: "#002BE7",
    keywords: ["hbo max", "streaming", "video"],
    loadIcon: () => import("@icongo/si/esm/SIMax").then((module) => module.SIMax),
  },
  {
    prefix: "lg",
    slug: "hulu",
    title: "Hulu",
    hex: "#1CE783",
    keywords: ["streaming", "video"],
    loadIcon: () => import("@icongo/si/esm/SIHulu").then((module) => module.SIHulu),
  },
  {
    prefix: "lg",
    slug: "instapaper",
    title: "Instapaper",
    hex: "#1F1F1F",
    keywords: ["read later", "articles", "news"],
    loadIcon: () => import("@icongo/si/esm/SIInstapaper").then((module) => module.SIInstapaper),
  },
  {
    prefix: "lg",
    slug: "mega",
    title: "Mega",
    hex: "#D9272E",
    keywords: ["cloud storage", "files"],
    loadIcon: () => import("@icongo/si/esm/SIMega").then((module) => module.SIMega),
  },
  {
    prefix: "custom",
    slug: "nintendo",
    title: "Nintendo",
    hex: "#E60012",
    keywords: ["gaming", "console", "switch"],
    loadIcon: () => Promise.resolve(SXNintendo),
  },
  {
    prefix: "custom",
    slug: "chinamobile",
    title: "China Mobile",
    hex: "#0080CB",
    keywords: ["中国移动", "telecom", "carrier"],
    loadIcon: () => Promise.resolve(SXChinaMobile),
  },
  {
    prefix: "custom",
    slug: "chinatelecom",
    title: "China Telecom",
    hex: "#005CA1",
    keywords: ["中国电信", "telecom", "carrier"],
    loadIcon: () => Promise.resolve(SXChinaTelecom),
  },
  {
    prefix: "custom",
    slug: "chinaunicom",
    title: "China Unicom",
    hex: "#E90003",
    keywords: ["中国联通", "telecom", "carrier"],
    loadIcon: () => Promise.resolve(SXChinaUnicom),
  },
  {
    prefix: "custom",
    slug: "chinabroadcast",
    title: "China Broadnet",
    hex: "#205686",
    keywords: ["中国广电", "telecom", "carrier"],
    loadIcon: () => Promise.resolve(SXChinaBroadcast),
  },
  {
    prefix: "lg",
    slug: "nordvpn",
    title: "NordVPN",
    hex: "#4687FF",
    keywords: ["vpn", "privacy", "security"],
    loadIcon: () => import("@icongo/si/esm/SINordvpn").then((module) => module.SINordvpn),
  },
  {
    prefix: "lg",
    slug: "notion",
    title: "Notion",
    hex: "#000000",
    keywords: ["notes", "workspace", "productivity"],
    loadIcon: () => import("@icongo/si/esm/SINotion").then((module) => module.SINotion),
  },
  {
    prefix: "lg",
    slug: "obsidian",
    title: "Obsidian",
    hex: "#7C3AED",
    keywords: ["notes", "markdown", "knowledge"],
    loadIcon: () => import("@icongo/si/esm/SIObsidian").then((module) => module.SIObsidian),
  },
  {
    prefix: "lg",
    slug: "openvpn",
    title: "OpenVPN",
    hex: "#EA7E20",
    keywords: ["vpn", "privacy", "security"],
    loadIcon: () => import("@icongo/si/esm/SIOpenvpn").then((module) => module.SIOpenvpn),
  },
  {
    prefix: "lg",
    slug: "playstation",
    title: "PlayStation",
    hex: "#003791",
    keywords: ["gaming", "console", "playstation"],
    loadIcon: () => import("@icongo/si/esm/SIPlaystation").then((module) => module.SIPlaystation),
  },
  {
    prefix: "lg",
    slug: "tmobile",
    title: "T-Mobile",
    hex: "#E20074",
    keywords: ["telecom", "mobile", "carrier"],
    loadIcon: () => import("@icongo/si/esm/SITmobile").then((module) => module.SITmobile),
  },
  {
    prefix: "lg",
    slug: "ubisoft",
    title: "Ubisoft",
    hex: "#000000",
    keywords: ["gaming", "games", "publisher"],
    loadIcon: () => import("@icongo/si/esm/SIUbisoft").then((module) => module.SIUbisoft),
  },
  {
    prefix: "custom",
    slug: "neteaseuu",
    title: "NetEase UU Booster",
    hex: "#36ECD4",
    keywords: ["网易UU加速器", "gaming", "booster"],
    loadIcon: () => Promise.resolve(SXNeteaseUu),
  },
  {
    prefix: "lg",
    slug: "unsplash",
    title: "Unsplash",
    hex: "#000000",
    keywords: ["photos", "images", "stock"],
    loadIcon: () => import("@icongo/si/esm/SIUnsplash").then((module) => module.SIUnsplash),
  },
  {
    prefix: "lg",
    slug: "crunchyroll",
    title: "Crunchyroll",
    hex: "#F47521",
    keywords: ["anime", "streaming", "video"],
    loadIcon: () => import("@icongo/si/esm/SICrunchyroll").then((module) => module.SICrunchyroll),
  },
  {
    prefix: "custom",
    slug: "dlsite",
    title: "DLsite",
    hex: "#0B3687",
    keywords: ["doujin", "digital store", "anime"],
    loadIcon: () => Promise.resolve(SXDlsite),
  },
  {
    prefix: "lg",
    slug: "niconico",
    title: "Niconico",
    hex: "#252525",
    keywords: ["ニコニコ動画", "japan", "video", "streaming"],
    loadIcon: () => import("@icongo/si/esm/SINiconico").then((module) => module.SINiconico),
  },
  {
    prefix: "custom",
    slug: "bilibili",
    title: "Bilibili",
    hex: "#1296DB",
    keywords: ["b站", "哔哩哔哩", "anime", "video", "streaming"],
    loadIcon: () => Promise.resolve(SXBilibili),
  },
  {
    prefix: "custom",
    slug: "iqiyi",
    title: "iQIYI",
    hex: "#42BD56",
    keywords: ["爱奇艺", "video", "streaming"],
    loadIcon: () => Promise.resolve(SXIqiyi),
  },
  {
    prefix: "lg",
    slug: "kuaishou",
    title: "Kuaishou",
    hex: "#FF4906",
    keywords: ["快手", "short video", "video", "streaming"],
    loadIcon: () => import("@icongo/si/esm/SIKuaishou").then((module) => module.SIKuaishou),
  },
  {
    prefix: "custom",
    slug: "neteasecloudmusic",
    title: "Netease Cloud Music",
    hex: "#DD001B",
    keywords: ["网易云音乐", "netease", "music", "streaming"],
    loadIcon: () => Promise.resolve(SXNeteaseCloudMusic),
  },
  {
    prefix: "lg",
    slug: "youtube",
    title: "YouTube",
    hex: "#FF0000",
    keywords: ["video"],
    loadIcon: () => import("@icongo/lg/esm/LGYoutubeIcon").then((module) => module.LGYoutubeIcon),
  },
  {
    prefix: "lg",
    slug: "spotify",
    title: "Spotify",
    hex: "#1DB954",
    keywords: ["music"],
    loadIcon: () => import("@icongo/lg/esm/LGSpotifyIcon").then((module) => module.LGSpotifyIcon),
  },
  {
    prefix: "lg",
    slug: "netflix",
    title: "Netflix",
    hex: "#E50914",
    keywords: ["video"],
    loadIcon: () => import("@icongo/vl/esm/VLNetflix").then((module) => module.VLNetflix),
  },
  {
    prefix: "lg",
    slug: "amazonprimevideo",
    title: "Amazon Prime Video",
    hex: "#00A8E1",
    keywords: ["amazon", "prime video", "video", "streaming"],
    loadIcon: () => import("@icongo/vl/esm/VLCprime").then((module) => module.VLCprime),
  },
  {
    prefix: "lg",
    slug: "appletvplus",
    title: "Apple TV+",
    hex: "#000000",
    keywords: ["apple tv", "tv+", "streaming", "video"],
    loadIcon: () => import("@icongo/lg/esm/LGApple").then((module) => module.LGApple),
  },
  {
    prefix: "lg",
    slug: "applemusic",
    title: "Apple Music",
    hex: "#FA2D48",
    keywords: ["apple", "music", "streaming"],
    loadIcon: () => import("@icongo/lg/esm/LGApple").then((module) => module.LGApple),
  },
  {
    prefix: "custom",
    slug: "youtubemusic",
    title: "YouTube Music",
    hex: "#FF0000",
    keywords: ["youtube", "music", "streaming"],
    loadIcon: () => Promise.resolve(SXYoutubeMusic),
  },
  {
    prefix: "custom",
    slug: "qqmusic",
    title: "QQ Music",
    hex: "#31C27C",
    keywords: ["qq", "qq音乐", "music", "腾讯音乐"],
    loadIcon: () => Promise.resolve(SXQqMusic),
  },
  {
    prefix: "custom",
    slug: "qq",
    title: "QQ",
    hex: "#000000",
    keywords: ["qq", "messaging", "腾讯"],
    loadIcon: () => Promise.resolve(SXQq),
  },
  {
    prefix: "custom",
    slug: "kugoumusic",
    title: "Kugou Music",
    hex: "#2C78FF",
    keywords: ["酷狗音乐", "kugou", "music", "腾讯音乐"],
    loadIcon: () => Promise.resolve(SXKugouMusic),
  },
  {
    prefix: "custom",
    slug: "ximalaya",
    title: "Ximalaya",
    hex: "#ED2400",
    keywords: ["喜马拉雅", "audio", "podcast"],
    loadIcon: () => Promise.resolve(SXXimalaya),
  },
  {
    prefix: "lg",
    slug: "disneyplus",
    title: "Disney+",
    hex: "#113CCF",
    keywords: ["disney", "streaming", "video", "迪士尼+", "流媒体"],
    loadIcon: () => import("@icongo/vl/esm/VLDisney").then((module) => module.VLDisney),
  },
  {
    prefix: "lg",
    slug: "twitch",
    title: "Twitch",
    hex: "#9146FF",
    keywords: ["streaming", "live", "gaming", "直播", "游戏直播"],
    loadIcon: () => import("@icongo/lg/esm/LGTwitch").then((module) => module.LGTwitch),
  },
  {
    prefix: "lg",
    slug: "vimeo",
    title: "Vimeo",
    hex: "#1AB7EA",
    keywords: ["video", "streaming"],
    loadIcon: () => import("@icongo/lg/esm/LGVimeoIcon").then((module) => module.LGVimeoIcon),
  },
  {
    prefix: "lg",
    slug: "soundcloud",
    title: "SoundCloud",
    hex: "#FF5500",
    keywords: ["music", "audio", "streaming", "音乐"],
    loadIcon: () => import("@icongo/lg/esm/LGSoundcloud").then((module) => module.LGSoundcloud),
  },
  {
    prefix: "lg",
    slug: "plex",
    title: "Plex",
    hex: "#E5A00D",
    keywords: ["media server", "streaming", "video"],
    loadIcon: () => import("@icongo/vl/esm/VLPlextv").then((module) => module.VLPlextv),
  },
  {
    prefix: "custom",
    slug: "infuse",
    title: "Infuse",
    hex: "#111111",
    keywords: ["media player", "video", "streaming"],
    loadIcon: () => Promise.resolve(SXInfuse),
  },
  {
    prefix: "custom",
    slug: "emby",
    title: "Emby",
    hex: "#06B831",
    keywords: ["media server", "streaming", "video"],
    loadIcon: () => Promise.resolve(SXEmby),
  },
  {
    prefix: "custom",
    slug: "jellyfin",
    title: "Jellyfin",
    hex: "#00A4DC",
    keywords: ["media server", "streaming", "video"],
    loadIcon: () => Promise.resolve(SXJellyfin),
  },
  {
    prefix: "lg",
    slug: "vlc",
    title: "VLC",
    hex: "#FF8800",
    keywords: ["videolan", "media player", "video", "播放器"],
    loadIcon: () => import("@icongo/vl/esm/VLVideolanVlc").then((module) => module.VLVideolanVlc),
  },
  {
    prefix: "custom",
    slug: "tencentvideo",
    title: "Tencent Video",
    hex: "#0052D9",
    keywords: ["tencent", "qq video", "腾讯视频", "视频", "流媒体"],
    loadIcon: () => Promise.resolve(SXTencentVideo),
  },
  {
    prefix: "lg",
    slug: "weibo",
    title: "Weibo",
    hex: "#E6162D",
    keywords: ["social", "video", "微博", "国内平台"],
    loadIcon: () => import("@icongo/vl/esm/VLWeibo").then((module) => module.VLWeibo),
  },
  {
    prefix: "lg",
    slug: "apple",
    title: "Apple",
    hex: "#000000",
    keywords: ["ios", "mac"],
    loadIcon: () => import("@icongo/lg/esm/LGAppleAppStore").then((module) => module.LGAppleAppStore),
  },
  {
    prefix: "lg",
    slug: "tiktok",
    title: "TikTok",
    hex: "#000000",
    keywords: ["short video"],
    loadIcon: () => import("@icongo/lg/esm/LGTiktokIcon").then((module) => module.LGTiktokIcon),
  },
  {
    prefix: "lg",
    slug: "discord",
    title: "Discord",
    hex: "#5865F2",
    keywords: ["chat"],
    loadIcon: () => import("@icongo/lg/esm/LGDiscordIcon").then((module) => module.LGDiscordIcon),
  },
  {
    prefix: "lg",
    slug: "line",
    title: "LINE",
    hex: "#00C300",
    keywords: ["chat", "messaging", "social"],
    loadIcon: () => import("@icongo/vl/esm/VLLine").then((module) => module.VLLine),
  },
  {
    prefix: "lg",
    slug: "telegram",
    title: "Telegram",
    hex: "#26A5E4",
    keywords: ["chat"],
    loadIcon: () => import("@icongo/lg/esm/LGTelegram").then((module) => module.LGTelegram),
  },
  {
    prefix: "lg",
    slug: "facebook",
    title: "Facebook",
    hex: "#1877F2",
    keywords: ["social"],
    loadIcon: () => import("@icongo/lg/esm/LGFacebook").then((module) => module.LGFacebook),
  },
  {
    prefix: "lg",
    slug: "instagram",
    title: "Instagram",
    hex: "#E4405F",
    keywords: ["social"],
    loadIcon: () => import("@icongo/lg/esm/LGInstagramIcon").then((module) => module.LGInstagramIcon),
  },
  {
    prefix: "lg",
    slug: "bitcoin",
    title: "Bitcoin",
    hex: "#F7931A",
    keywords: ["btc", "crypto"],
    loadIcon: () => import("@icongo/lg/esm/LGBitcoin").then((module) => module.LGBitcoin),
  },
  {
    prefix: "custom",
    slug: "okx",
    title: "OKX",
    hex: "#111111",
    keywords: ["crypto", "exchange", "okx"],
    loadIcon: () => Promise.resolve(SXOkx),
  },
  {
    prefix: "custom",
    slug: "binance",
    title: "Binance",
    hex: "#F3BA2F",
    keywords: ["crypto", "exchange", "binance"],
    loadIcon: () => Promise.resolve(SXBinance),
  },
  {
    prefix: "lg",
    slug: "ethereum",
    title: "Ethereum",
    hex: "#3C3C3D",
    keywords: ["eth", "crypto"],
    loadIcon: () => import("@icongo/lg/esm/LGEthereum").then((module) => module.LGEthereum),
  },
  {
    prefix: "lg",
    slug: "monero",
    title: "Monero",
    hex: "#FF6600",
    keywords: ["xmr", "crypto"],
    loadIcon: () => import("@icongo/lg/esm/LGMonero").then((module) => module.LGMonero),
  },
  {
    prefix: "lg",
    slug: "kraken",
    title: "Kraken",
    hex: "#5741D9",
    keywords: ["exchange", "crypto"],
    loadIcon: () => import("@icongo/lg/esm/LGKraken").then((module) => module.LGKraken),
  },
  {
    prefix: "custom",
    slug: "game",
    title: "Game",
    hex: "#4A4A4A",
    keywords: ["gaming", "gamepad", "controller"],
    loadIcon: () => Promise.resolve(SXGame),
  },
]
