import { SXAfdian } from "../custom/afdian"
import { SXAdobeCreativeCloud } from "../custom/adobecreativecloud"
import { SXAliyunDrive } from "../custom/aliyundrive"
import { SXBaiduNetdisk } from "../custom/baidunetdisk"
import { SXBitwarden } from "../custom/bitwarden"
import { SXCamscanner } from "../custom/camscanner"
import { SXChina12306 } from "../custom/china12306"
import { SXCoinbase } from "../custom/coinbase"
import { SXCsdn } from "../custom/csdn"
import { SXDrive115 } from "../custom/drive115"
import { SXDrive123 } from "../custom/drive123"
import { SXFeiniu } from "../custom/feiniu"
import { SXFeishu } from "../custom/feishu"
import { SXGodaddy } from "../custom/godaddy"
import { SXHelloBike } from "../custom/hellobike"
import { SXIcloud } from "../custom/icloud"
import { SXJd } from "../custom/jd"
import { SXJuejin } from "../custom/juejin"
import { SXLeetcode } from "../custom/leetcode"
import { SXMeituan } from "../custom/meituan"
import { SXOnlyFans } from "../custom/onlyfans"
import { SXPikpak } from "../custom/pikpak"
import { SXPinduoduo } from "../custom/pinduoduo"
import { SXQuarkDrive } from "../custom/quarkdrive"
import { SXSamsClub } from "../custom/samsclub"
import { SXTaobao } from "../custom/taobao"
import { SXTickTick } from "../custom/ticktick"
import { SXVip88 } from "../custom/vip88"
import { SXWeiyun } from "../custom/weiyun"
import { SXWpsOffice } from "../custom/wpsoffice"
import { SXX } from "../custom/x"
import { SXXiaomiCloud } from "../custom/xiaomicloud"
import { SXXunlei } from "../custom/xunlei"
import { SXYuque } from "../custom/yuque"
import { SXZhihu } from "../custom/zhihu"

import type { BrandIconSpec } from "../types"

export const serviceBrandSpecs: BrandIconSpec[] = [
  {
    prefix: "lg",
    slug: "onepassword",
    title: "1Password",
    hex: "#0094F5",
    keywords: ["password manager", "security", "密码管理"],
    loadIcon: () => import("@icongo/vl/esm/VL1Password").then((module) => module.VL1Password),
  },
  {
    prefix: "lg",
    slug: "adidas",
    title: "Adidas",
    hex: "#000000",
    keywords: ["sportswear", "brand"],
    loadIcon: () => import("@icongo/vl/esm/VLAdidas").then((module) => module.VLAdidas),
  },
  {
    prefix: "custom",
    slug: "adobecreativecloud",
    title: "Adobe Creative Cloud",
    hex: "#DA1F26",
    keywords: ["adobe", "creative", "design", "创意云"],
    loadIcon: () => Promise.resolve(SXAdobeCreativeCloud),
  },
  {
    prefix: "lg",
    slug: "adobeaftereffects",
    title: "Adobe After Effects",
    hex: "#9999FF",
    keywords: ["adobe", "video", "motion", "ae"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeAfterEffects").then((module) => module.LGAdobeAfterEffects),
  },
  {
    prefix: "lg",
    slug: "adobeanimate",
    title: "Adobe Animate",
    hex: "#FF8B00",
    keywords: ["adobe", "animation"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeAnimate").then((module) => module.LGAdobeAnimate),
  },
  {
    prefix: "lg",
    slug: "adobedreamweaver",
    title: "Adobe Dreamweaver",
    hex: "#35FA00",
    keywords: ["adobe", "web", "development"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeDreamweaver").then((module) => module.LGAdobeDreamweaver),
  },
  {
    prefix: "lg",
    slug: "adobeillustrator",
    title: "Adobe Illustrator",
    hex: "#FF9A00",
    keywords: ["adobe", "vector", "design", "ai"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeIllustrator").then((module) => module.LGAdobeIllustrator),
  },
  {
    prefix: "lg",
    slug: "adobeincopy",
    title: "Adobe InCopy",
    hex: "#FF3366",
    keywords: ["adobe", "writing", "editorial"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeIncopy").then((module) => module.LGAdobeIncopy),
  },
  {
    prefix: "lg",
    slug: "adobeindesign",
    title: "Adobe InDesign",
    hex: "#FF3366",
    keywords: ["adobe", "layout", "publishing", "id"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeIndesign").then((module) => module.LGAdobeIndesign),
  },
  {
    prefix: "lg",
    slug: "adobelightroom",
    title: "Adobe Lightroom",
    hex: "#31A8FF",
    keywords: ["adobe", "photo", "editing", "lr"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeLightroom").then((module) => module.LGAdobeLightroom),
  },
  {
    prefix: "lg",
    slug: "adobephotoshop",
    title: "Adobe Photoshop",
    hex: "#31A8FF",
    keywords: ["adobe", "photo", "design", "ps"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobePhotoshop").then((module) => module.LGAdobePhotoshop),
  },
  {
    prefix: "lg",
    slug: "adobepremiere",
    title: "Adobe Premiere Pro",
    hex: "#9999FF",
    keywords: ["adobe", "video", "editing", "pr"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobePremiere").then((module) => module.LGAdobePremiere),
  },
  {
    prefix: "lg",
    slug: "adobexd",
    title: "Adobe XD",
    hex: "#FF61F6",
    keywords: ["adobe", "ux", "ui", "design"],
    loadIcon: () => import("@icongo/lg/esm/LGAdobeXd").then((module) => module.LGAdobeXd),
  },
  {
    prefix: "lg",
    slug: "airbnb",
    title: "Airbnb",
    hex: "#FF5A5F",
    keywords: ["travel", "booking", "住宿"],
    loadIcon: () => import("@icongo/lg/esm/LGAirbnbIcon").then((module) => module.LGAirbnbIcon),
  },
  {
    prefix: "lg",
    slug: "behance",
    title: "Behance",
    hex: "#1769FF",
    keywords: ["design", "portfolio"],
    loadIcon: () => import("@icongo/vl/esm/VLBehance").then((module) => module.VLBehance),
  },
  {
    prefix: "custom",
    slug: "bitwarden",
    title: "Bitwarden",
    hex: "#175DDC",
    keywords: ["password manager", "security", "密码管理"],
    loadIcon: () => Promise.resolve(SXBitwarden),
  },
  {
    prefix: "lg",
    slug: "box",
    title: "Box",
    hex: "#0061D5",
    keywords: ["cloud storage", "files"],
    loadIcon: () => import("@icongo/lg/esm/LGBox").then((module) => module.LGBox),
  },
  {
    prefix: "custom",
    slug: "baidunetdisk",
    title: "Baidu Netdisk",
    hex: "#06A7FF",
    keywords: ["百度网盘", "cloud storage", "drive"],
    loadIcon: () => Promise.resolve(SXBaiduNetdisk),
  },
  {
    prefix: "lg",
    slug: "canva",
    title: "Canva",
    hex: "#00C4CC",
    keywords: ["design", "graphics"],
    loadIcon: () => import("@icongo/vl/esm/VLCanva").then((module) => module.VLCanva),
  },
  {
    prefix: "custom",
    slug: "coinbase",
    title: "Coinbase",
    hex: "#0052FF",
    keywords: ["crypto", "exchange", "coin"],
    loadIcon: () => Promise.resolve(SXCoinbase),
  },
  {
    prefix: "lg",
    slug: "dropbox",
    title: "Dropbox",
    hex: "#0061FF",
    keywords: ["cloud storage", "files"],
    loadIcon: () => import("@icongo/lg/esm/LGDropbox").then((module) => module.LGDropbox),
  },
  {
    prefix: "custom",
    slug: "quarkdrive",
    title: "Quark Drive",
    hex: "#3A25DD",
    keywords: ["夸克网盘", "cloud storage", "drive"],
    loadIcon: () => Promise.resolve(SXQuarkDrive),
  },
  {
    prefix: "custom",
    slug: "aliyundrive",
    title: "Aliyun Drive",
    hex: "#6666FF",
    keywords: ["阿里云盘", "cloud storage", "drive"],
    loadIcon: () => Promise.resolve(SXAliyunDrive),
  },
  {
    prefix: "custom",
    slug: "drive115",
    title: "115 Drive",
    hex: "#224888",
    keywords: ["115网盘", "cloud storage", "drive"],
    loadIcon: () => Promise.resolve(SXDrive115),
  },
  {
    prefix: "custom",
    slug: "drive123",
    title: "123 Drive",
    hex: "#597DFC",
    keywords: ["123网盘", "cloud storage", "drive"],
    loadIcon: () => Promise.resolve(SXDrive123),
  },
  {
    prefix: "custom",
    slug: "weiyun",
    title: "Tencent Weiyun",
    hex: "#2980FF",
    keywords: ["腾讯微云", "cloud storage", "drive"],
    loadIcon: () => Promise.resolve(SXWeiyun),
  },
  {
    prefix: "custom",
    slug: "xiaomicloud",
    title: "Xiaomi Cloud",
    hex: "#1296DB",
    keywords: ["小米云空间", "xiaomi", "cloud storage", "drive"],
    loadIcon: () => Promise.resolve(SXXiaomiCloud),
  },
  {
    prefix: "custom",
    slug: "xunlei",
    title: "Xunlei",
    hex: "#1390F2",
    keywords: ["迅雷", "download", "cloud storage"],
    loadIcon: () => Promise.resolve(SXXunlei),
  },
  {
    prefix: "custom",
    slug: "pikpak",
    title: "PikPak",
    hex: "#306EFF",
    keywords: ["pikpak", "cloud storage", "drive"],
    loadIcon: () => Promise.resolve(SXPikpak),
  },
  {
    prefix: "lg",
    slug: "evernote",
    title: "Evernote",
    hex: "#00A82D",
    keywords: ["notes", "productivity"],
    loadIcon: () => import("@icongo/vl/esm/VLEvernote").then((module) => module.VLEvernote),
  },
  {
    prefix: "lg",
    slug: "expressvpn",
    title: "ExpressVPN",
    hex: "#DA3940",
    keywords: ["vpn", "privacy", "security"],
    loadIcon: () => import("@icongo/si/esm/SIExpressvpn").then((module) => module.SIExpressvpn),
  },
  {
    prefix: "lg",
    slug: "feedly",
    title: "Feedly",
    hex: "#2BB24C",
    keywords: ["rss", "reader", "news"],
    loadIcon: () => import("@icongo/vl/esm/VLFeedly").then((module) => module.VLFeedly),
  },
  {
    prefix: "custom",
    slug: "feishu",
    title: "Feishu",
    hex: "#296DFF",
    keywords: ["lark", "im", "collaboration", "飞书"],
    loadIcon: () => Promise.resolve(SXFeishu),
  },
  {
    prefix: "custom",
    slug: "feiniu",
    title: "Feiniu",
    hex: "#2668ED",
    keywords: ["fnos", "nas", "飞牛"],
    loadIcon: () => Promise.resolve(SXFeiniu),
  },
  {
    prefix: "lg",
    slug: "fontawesome",
    title: "Font Awesome",
    hex: "#528DD7",
    keywords: ["icons", "font", "ui"],
    loadIcon: () => import("@icongo/lg/esm/LGFontAwesome").then((module) => module.LGFontAwesome),
  },
  {
    prefix: "custom",
    slug: "camscanner",
    title: "CamScanner",
    hex: "#3A86FF",
    keywords: ["scan", "document", "pdf"],
    loadIcon: () => Promise.resolve(SXCamscanner),
  },
  {
    prefix: "custom",
    slug: "godaddy",
    title: "GoDaddy",
    hex: "#1BDBDB",
    keywords: ["domain", "hosting"],
    loadIcon: () => Promise.resolve(SXGodaddy),
  },
  {
    prefix: "lg",
    slug: "googleone",
    title: "Google One",
    hex: "#4285F4",
    keywords: ["google", "cloud storage", "drive"],
    loadIcon: () => import("@icongo/lg/esm/LGGoogleOne").then((module) => module.LGGoogleOne),
  },
  {
    prefix: "lg",
    slug: "grammarly",
    title: "Grammarly",
    hex: "#15C39A",
    keywords: ["writing", "assistant", "grammar"],
    loadIcon: () => import("@icongo/lg/esm/LGGrammarlyIcon").then((module) => module.LGGrammarlyIcon),
  },
  {
    prefix: "custom",
    slug: "wpsoffice",
    title: "WPS Office",
    hex: "#FE3E53",
    keywords: ["wps", "office", "document", "金山办公"],
    loadIcon: () => Promise.resolve(SXWpsOffice),
  },
  {
    prefix: "custom",
    slug: "yuque",
    title: "Yuque",
    hex: "#31CC79",
    keywords: ["语雀", "docs", "knowledge base"],
    loadIcon: () => Promise.resolve(SXYuque),
  },
  {
    prefix: "custom",
    slug: "ticktick",
    title: "TickTick",
    hex: "#617FDE",
    keywords: ["滴答清单", "todo", "task management"],
    loadIcon: () => Promise.resolve(SXTickTick),
  },
  {
    prefix: "custom",
    slug: "hellobike",
    title: "HelloBike",
    hex: "#1890FF",
    keywords: ["哈啰单车", "bike sharing", "transport"],
    loadIcon: () => Promise.resolve(SXHelloBike),
  },
  {
    prefix: "custom",
    slug: "china12306",
    title: "China Railway 12306",
    hex: "#F95858",
    keywords: ["railway", "train", "12306", "中国铁路"],
    loadIcon: () => Promise.resolve(SXChina12306),
  },
  {
    prefix: "lg",
    slug: "udemy",
    title: "Udemy",
    hex: "#A435F0",
    keywords: ["learning", "courses", "education"],
    loadIcon: () => import("@icongo/lg/esm/LGUdemyIcon").then((module) => module.LGUdemyIcon),
  },
  {
    prefix: "custom",
    slug: "leetcode",
    title: "LeetCode",
    hex: "#EAA240",
    keywords: ["coding", "algorithm", "interview"],
    loadIcon: () => Promise.resolve(SXLeetcode),
  },
  {
    prefix: "lg",
    slug: "jetbrains",
    title: "JetBrains",
    hex: "#000000",
    keywords: ["ide", "developer tools", "jetbrains"],
    loadIcon: () => import("@icongo/lg/esm/LGJetbrainsIcon").then((module) => module.LGJetbrainsIcon),
  },
  {
    prefix: "custom",
    slug: "juejin",
    title: "Juejin",
    hex: "#006CFF",
    keywords: ["掘金", "developer", "community", "articles"],
    loadIcon: () => Promise.resolve(SXJuejin),
  },
  {
    prefix: "custom",
    slug: "csdn",
    title: "CSDN",
    hex: "#C61C22",
    keywords: ["csdn", "developer", "community", "articles", "博客"],
    loadIcon: () => Promise.resolve(SXCsdn),
  },
  {
    prefix: "lg",
    slug: "intellijidea",
    title: "IntelliJ IDEA",
    hex: "#000000",
    keywords: ["jetbrains", "ide", "java", "intellij"],
    loadIcon: () => import("@icongo/lg/esm/LGIntellijIdea").then((module) => module.LGIntellijIdea),
  },
  {
    prefix: "lg",
    slug: "lastpass",
    title: "LastPass",
    hex: "#D32D27",
    keywords: ["password manager", "security", "密码管理"],
    loadIcon: () => import("@icongo/vl/esm/VLLastpass").then((module) => module.VLLastpass),
  },
  {
    prefix: "lg",
    slug: "linkedin",
    title: "LinkedIn",
    hex: "#0A66C2",
    keywords: ["social", "network", "career"],
    loadIcon: () => import("@icongo/lg/esm/LGLinkedinIcon").then((module) => module.LGLinkedinIcon),
  },
  {
    prefix: "lg",
    slug: "medium",
    title: "Medium",
    hex: "#12100E",
    keywords: ["blog", "writing", "articles"],
    loadIcon: () => import("@icongo/lg/esm/LGMediumIcon").then((module) => module.LGMediumIcon),
  },
  {
    prefix: "custom",
    slug: "meituan",
    title: "Meituan",
    hex: "#FFC300",
    keywords: ["美团", "food delivery", "local services"],
    loadIcon: () => Promise.resolve(SXMeituan),
  },
  {
    prefix: "lg",
    slug: "meta",
    title: "Meta",
    hex: "#0866FF",
    keywords: ["facebook", "social", "meta"],
    loadIcon: () => import("@icongo/si/esm/SIMeta").then((module) => module.SIMeta),
  },
  {
    prefix: "lg",
    slug: "nytimes",
    title: "New York Times",
    hex: "#000000",
    keywords: ["news", "times", "newspaper"],
    loadIcon: () => import("@icongo/vl/esm/VLNytimes").then((module) => module.VLNytimes),
  },
  {
    prefix: "lg",
    slug: "patreon",
    title: "Patreon",
    hex: "#FF424D",
    keywords: ["creator", "membership", "subscription"],
    loadIcon: () => import("@icongo/lg/esm/LGPatreon").then((module) => module.LGPatreon),
  },
  {
    prefix: "custom",
    slug: "afdian",
    title: "Afdian",
    hex: "#8F66DF",
    keywords: ["爱发电", "creator", "membership"],
    loadIcon: () => Promise.resolve(SXAfdian),
  },
  {
    prefix: "custom",
    slug: "onlyfans",
    title: "OnlyFans",
    hex: "#00AFF0",
    keywords: ["creator", "subscription", "membership"],
    loadIcon: () => Promise.resolve(SXOnlyFans),
  },
  {
    prefix: "lg",
    slug: "pixiv",
    title: "Pixiv",
    hex: "#0096FA",
    keywords: ["art", "illustration", "community"],
    loadIcon: () => import("@icongo/si/esm/SIPixiv").then((module) => module.SIPixiv),
  },
  {
    prefix: "lg",
    slug: "pinterest",
    title: "Pinterest",
    hex: "#E60023",
    keywords: ["social", "inspiration", "images"],
    loadIcon: () => import("@icongo/lg/esm/LGPinterest").then((module) => module.LGPinterest),
  },
  {
    prefix: "lg",
    slug: "proton",
    title: "Proton",
    hex: "#6D4AFF",
    keywords: ["protonmail", "privacy", "email"],
    loadIcon: () => import("@icongo/vl/esm/VLProtonmail").then((module) => module.VLProtonmail),
  },
  {
    prefix: "lg",
    slug: "revolut",
    title: "Revolut",
    hex: "#191C1F",
    keywords: ["banking", "finance", "payment"],
    loadIcon: () => import("@icongo/vl/esm/VLRevolut").then((module) => module.VLRevolut),
  },
  {
    prefix: "lg",
    slug: "twitter",
    title: "Twitter",
    hex: "#000000",
    keywords: ["twitter", "x", "social"],
    loadIcon: () => import("@icongo/lg/esm/LGTwitter").then((module) => module.LGTwitter),
  },
  {
    prefix: "custom",
    slug: "x",
    title: "X",
    hex: "#000000",
    keywords: ["twitter", "x", "social"],
    loadIcon: () => Promise.resolve(SXX),
  },
  {
    prefix: "lg",
    slug: "uber",
    title: "Uber",
    hex: "#000000",
    keywords: ["ride", "transport", "travel"],
    loadIcon: () => import("@icongo/si/esm/SIUber").then((module) => module.SIUber),
  },
  {
    prefix: "lg",
    slug: "walmart",
    title: "Walmart",
    hex: "#0071CE",
    keywords: ["shopping", "retail", "groceries"],
    loadIcon: () => import("@icongo/vl/esm/VLWalmart").then((module) => module.VLWalmart),
  },
  {
    prefix: "custom",
    slug: "samsclub",
    title: "Sam's Club",
    hex: "#5F6165",
    keywords: ["山姆", "shopping", "retail"],
    loadIcon: () => Promise.resolve(SXSamsClub),
  },
  {
    prefix: "custom",
    slug: "pinduoduo",
    title: "Pinduoduo",
    hex: "#D81E06",
    keywords: ["拼多多", "shopping", "ecommerce"],
    loadIcon: () => Promise.resolve(SXPinduoduo),
  },
  {
    prefix: "custom",
    slug: "taobao",
    title: "Taobao",
    hex: "#FC8848",
    keywords: ["淘宝", "shopping", "ecommerce"],
    loadIcon: () => Promise.resolve(SXTaobao),
  },
  {
    prefix: "custom",
    slug: "jd",
    title: "JD.com",
    hex: "#D81E06",
    keywords: ["京东", "shopping", "ecommerce"],
    loadIcon: () => Promise.resolve(SXJd),
  },
  {
    prefix: "custom",
    slug: "vip88",
    title: "88VIP",
    hex: "#DEC6AF",
    keywords: ["88vip", "membership", "taobao"],
    loadIcon: () => Promise.resolve(SXVip88),
  },
  {
    prefix: "lg",
    slug: "wise",
    title: "Wise",
    hex: "#9fe970",
    keywords: ["transferwise", "payment", "money transfer"],
    loadIcon: () => import("@icongo/vl/esm/VLTransferwise").then((module) => module.VLTransferwise),
  },
  {
    prefix: "lg",
    slug: "xbox",
    title: "Xbox",
    hex: "#107C10",
    keywords: ["gaming", "microsoft", "console"],
    loadIcon: () => import("@icongo/vl/esm/VLXbox").then((module) => module.VLXbox),
  },
  {
    prefix: "lg",
    slug: "zoom",
    title: "Zoom",
    hex: "#2D8CFF",
    keywords: ["meeting", "video call", "conference"],
    loadIcon: () => import("@icongo/vl/esm/VLZoomus").then((module) => module.VLZoomus),
  },
  {
    prefix: "custom",
    slug: "zhihu",
    title: "Zhihu",
    hex: "#0E87EA",
    keywords: ["知乎", "community", "q&a"],
    loadIcon: () => Promise.resolve(SXZhihu),
  },
  {
    prefix: "custom",
    slug: "icloud",
    title: "iCloud",
    hex: "#0A84FF",
    keywords: ["apple", "cloud storage", "icloud"],
    loadIcon: () => Promise.resolve(SXIcloud),
  },
]
