package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strconv"
)

type metadata struct {
	Currencies []currency `json:"currencies"`
}

type currency struct {
	Code        string `json:"code"`
	Exponent    *int   `json:"exponent,omitempty"`
	Wallos      bool   `json:"wallos,omitempty"`
	PresetOrder *int   `json:"preset_order,omitempty"`
}

type generatedFile struct {
	path    string
	content []byte
}

var currencyCodePattern = regexp.MustCompile(`^[A-Z]{3}$`)

func main() {
	check := flag.Bool("check", false, "fail when generated currency metadata is stale")
	flag.Parse()

	root, err := repositoryRoot()
	exitOnError(err)

	sourcePath := filepath.Join(root, "internal", "service", "money", "currency_metadata.json")
	source, err := os.ReadFile(sourcePath)
	exitOnError(err)

	var data metadata
	if err := json.Unmarshal(source, &data); err != nil {
		exitOnError(fmt.Errorf("decode %s: %w", sourcePath, err))
	}
	exitOnError(validate(data))

	files := []generatedFile{
		{
			path:    filepath.Join(root, "internal", "service", "money", "currency_metadata_generated.go"),
			content: generateMoneyMetadata(data),
		},
		{
			path:    filepath.Join(root, "internal", "service", "importer", "currency_metadata_generated.go"),
			content: generateImporterMetadata(data),
		},
		{
			path:    filepath.Join(root, "web", "src", "lib", "currency-metadata.generated.ts"),
			content: generateWebMetadata(data),
		},
	}

	for _, file := range files {
		if *check {
			current, err := os.ReadFile(file.path)
			if err != nil {
				exitOnError(fmt.Errorf("%s is missing or unreadable: %w", file.path, err))
			}
			if !bytes.Equal(current, file.content) {
				exitOnError(fmt.Errorf("%s is stale; run go generate ./internal/service/money", file.path))
			}
			continue
		}
		exitOnError(os.WriteFile(file.path, file.content, 0o644))
	}
}

func repositoryRoot() (string, error) {
	_, sourceFile, _, ok := runtime.Caller(0)
	if !ok {
		return "", errors.New("locate generator source")
	}

	for dir := filepath.Dir(sourceFile); ; dir = filepath.Dir(dir) {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("locate repository root containing go.mod")
		}
	}
}

func validate(data metadata) error {
	if len(data.Currencies) == 0 {
		return errors.New("currency metadata is empty")
	}

	seenCodes := make(map[string]struct{}, len(data.Currencies))
	presetOrders := make(map[int]string)
	maxPresetOrder := 0
	for _, item := range data.Currencies {
		if !currencyCodePattern.MatchString(item.Code) {
			return fmt.Errorf("currency code %q must be three uppercase ASCII letters", item.Code)
		}
		if _, exists := seenCodes[item.Code]; exists {
			return fmt.Errorf("currency code %q is duplicated", item.Code)
		}
		seenCodes[item.Code] = struct{}{}

		if item.Exponent != nil && (*item.Exponent < 0 || *item.Exponent > 4) {
			return fmt.Errorf("currency %s exponent %d is outside the supported 0..4 range", item.Code, *item.Exponent)
		}
		if item.PresetOrder == nil {
			continue
		}
		if *item.PresetOrder < 1 {
			return fmt.Errorf("currency %s preset_order must be positive", item.Code)
		}
		if other, exists := presetOrders[*item.PresetOrder]; exists {
			return fmt.Errorf("currencies %s and %s share preset_order %d", other, item.Code, *item.PresetOrder)
		}
		presetOrders[*item.PresetOrder] = item.Code
		if *item.PresetOrder > maxPresetOrder {
			maxPresetOrder = *item.PresetOrder
		}
	}

	for order := 1; order <= maxPresetOrder; order++ {
		if _, exists := presetOrders[order]; !exists {
			return fmt.Errorf("preset_order %d is missing", order)
		}
	}
	return nil
}

func generateMoneyMetadata(data metadata) []byte {
	var output bytes.Buffer
	output.WriteString("// Code generated by internal/service/money/cmd/generate; DO NOT EDIT.\n\n")
	output.WriteString("package money\n\n")
	output.WriteString("var currencyExponents = map[string]int{\n")
	for _, item := range data.Currencies {
		if item.Exponent == nil || *item.Exponent == 2 {
			continue
		}
		fmt.Fprintf(&output, "\t%q: %d,\n", item.Code, *item.Exponent)
	}
	output.WriteString("}\n")

	formatted, err := format.Source(output.Bytes())
	exitOnError(err)
	return formatted
}

func generateImporterMetadata(data metadata) []byte {
	var output bytes.Buffer
	output.WriteString("// Code generated by internal/service/money/cmd/generate; DO NOT EDIT.\n\n")
	output.WriteString("package importer\n\n")
	output.WriteString("var knownCurrencies = []string{\n")
	for _, item := range data.Currencies {
		if item.Wallos {
			fmt.Fprintf(&output, "\t%q,\n", item.Code)
		}
	}
	output.WriteString("}\n")

	formatted, err := format.Source(output.Bytes())
	exitOnError(err)
	return formatted
}

func generateWebMetadata(data metadata) []byte {
	presets := make([]currency, 0)
	for _, item := range data.Currencies {
		if item.PresetOrder != nil {
			presets = append(presets, item)
		}
	}
	sort.Slice(presets, func(i, j int) bool {
		return *presets[i].PresetOrder < *presets[j].PresetOrder
	})

	var output bytes.Buffer
	output.WriteString("// Code generated by internal/service/money/cmd/generate; DO NOT EDIT.\n\n")
	output.WriteString("export const PRESET_CURRENCY_CODES = [\n")
	for _, item := range presets {
		fmt.Fprintf(&output, "  %s,\n", strconv.Quote(item.Code))
	}
	output.WriteString("] as const\n\n")
	output.WriteString("export const CURRENCY_EXPONENTS: Readonly<Record<string, number>> = {\n")
	for _, item := range data.Currencies {
		if item.Exponent == nil || *item.Exponent == 2 {
			continue
		}
		fmt.Fprintf(&output, "  %s: %d,\n", strconv.Quote(item.Code), *item.Exponent)
	}
	output.WriteString("}\n")
	return output.Bytes()
}

func exitOnError(err error) {
	if err == nil {
		return
	}
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
