// Code generated by internal/service/money/cmd/generate; DO NOT EDIT.

package money

var currencyExponents = map[string]int{
	"JPY": 0,
	"KRW": 0,
	"ISK": 0,
	"KWD": 3,
	"BHD": 3,
	"OMR": 3,
	"JOD": 3,
	"TND": 3,
	"LYD": 3,
	"VND": 0,
	"CLP": 0,
	"UYI": 0,
	"BIF": 0,
	"DJF": 0,
	"GNF": 0,
	"KMF": 0,
	"PYG": 0,
	"RWF": 0,
	"UGX": 0,
	"VUV": 0,
	"XAF": 0,
	"XOF": 0,
	"XPF": 0,
	"IQD": 3,
	"CLF": 4,
	"UYW": 4,
}
